'use strict';
const sections={overview:['Resumen','El estado de tu negocio en un solo lugar.','Indicadores del negocio','Usuarios activos, ingresos, costos y margen del período.'],users:['Usuarios','Administra cuentas gratuitas y de pago.','Gestión de usuarios','Cuentas, email confirmado, plan, estado y consumo.'],plans:['Planes y rentabilidad','Compara lo que incluye cada plan.','Planes, precios y ganancias','Precio de venta, funciones incluidas, límites, costo por usuario y margen.'],usage:['Uso y costos','Comprende el consumo y los costos de NUNA.','Consumo de IA','Uso por tarea, cuenta y plan; costos internos de los servicios utilizados.'],billing:['Facturación','Consulta ingresos y el estado de los pagos.','Pagos y facturas','Suscripciones, cobros, facturas y reembolsos.'],permissions:['Permisos','Controla quién puede administrar NUNA.','Acceso administrativo','Solo las cuentas autorizadas por el servidor pueden entrar. Los usuarios normales no tienen acceso.']};
let client=null,verification=0;
const notice=document.getElementById('notice'),submit=document.getElementById('submit');submit.disabled=true;
function showLogin(message){verification++;document.getElementById('workspace').hidden=true;document.getElementById('login').hidden=false;notice.textContent=message;submit.disabled=!client;document.getElementById('account-email').textContent=''}
function showSection(id){const s=sections[id]||sections.overview;['section-title','section-description','panel-title','panel-description'].forEach((key,i)=>document.getElementById(key).textContent=s[i]);document.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-current',b.dataset.section===id?'page':'false'))}
async function verify(session){
 const attempt=++verification;
 if(!session?.access_token){showLogin('Inicia sesión con tu cuenta administradora.');return}
 try{const r=await fetch('/api/admin',{headers:{Authorization:'Bearer '+session.access_token},cache:'no-store',signal:AbortSignal.timeout(10000)});if(attempt!==verification)return;if(!r.ok){showLogin(r.status===403?'Esta cuenta no tiene permiso para administrar NUNA.':r.status===401?'Inicia sesión con email confirmado.':'No se pudo verificar el acceso. Inténtalo de nuevo.');return}const data=await r.json();if(attempt!==verification)return;document.getElementById('password').value='';document.getElementById('account-email').textContent=data.administrator.email;document.getElementById('login').hidden=true;document.getElementById('workspace').hidden=false;showSection('overview')}catch{showLogin('No se pudo verificar el acceso. Inténtalo de nuevo.')}
}
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>showSection(b.dataset.section));
document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();if(!client)return;submit.disabled=true;notice.textContent='Verificando acceso…';try{const {data,error}=await client.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(error){showLogin('No se pudo iniciar sesión. Comprueba tu email, contraseña y confirmación de email.');return}await verify(data.session)}catch{showLogin('No se pudo conectar. Inténtalo de nuevo.')}finally{submit.disabled=false}};
document.getElementById('logout').onclick=async()=>{showLogin('Cerrando sesión…');try{await client.auth.signOut({scope:'local'})}finally{showLogin('Sesión cerrada.')}};
(async()=>{try{const r=await fetch('/api/config',{cache:'no-store'});if(!r.ok)throw Error();const config=await r.json();if(!config.supabase||!window.supabase?.createClient)throw Error();client=window.supabase.createClient(config.supabase.url,config.supabase.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'nuna-admin-auth'}});client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showLogin('Sesión cerrada.');if(event==='TOKEN_REFRESHED')verify(session)});const {data}=await client.auth.getSession();await verify(data.session)}catch{showLogin('No se pudo preparar el acceso. Recarga la página.')}})();
