let pendingAttachments=[];const attachmentMenu=document.getElementById('attachment-menu');const attachmentPreview=document.getElementById('attachment-preview');const attachmentButton=document.getElementById('attach-open');const attachmentInput=document.createElement('input');attachmentInput.type='file';attachmentInput.multiple=true;attachmentInput.hidden=true;document.body.append(attachmentInput);
function renderChatAttachments(container,files){const list=document.createElement('div');list.className='chat-files';files.forEach(file=>{const card=document.createElement('div');card.className='file-chip';if(file.preview){card.classList.add('photo-chip');card.title=file.name;const img=document.createElement('img');img.src=file.preview;img.alt=file.name;card.append(img)}const name=document.createElement('span');name.textContent=file.name;const size=document.createElement('small');size.textContent=(file.size/1024).toFixed(1)+' KB';card.append(name,size);list.append(card)});container.append(list)}
document.getElementById('composer').prepend(attachmentPreview);
async function attachmentThumbnail(file){const url=URL.createObjectURL(file);try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});const canvas=document.createElement('canvas'),scale=Math.min(1,240/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.8)}finally{URL.revokeObjectURL(url)}}
function refreshAttachments(){attachmentPreview.replaceChildren();attachmentPreview.hidden=!pendingAttachments.length;pendingAttachments.forEach((file,i)=>{const card=document.createElement('div');card.className='file-chip';if(file.preview){card.classList.add('photo-chip');card.title=file.name;const img=document.createElement('img');img.src=file.preview;img.alt=file.name;card.append(img)}const name=document.createElement('span');name.textContent=file.name;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',(lang==='es'?'Quitar ':'Remove ')+file.name);remove.onclick=()=>{pendingAttachments.splice(i,1);refreshAttachments()};card.append(name,remove);attachmentPreview.append(card)});document.getElementById('send').disabled=!pendingAttachments.length&&!document.getElementById('prompt').value.trim()}
let attachmentUploadQueue=Promise.resolve();
function addAttachmentFiles(files){const owner=authUser?.id;const list=[...files];const job=attachmentUploadQueue.then(async()=>{for(const file of list){if(authUser?.id!==owner)break;if(pendingAttachments.length>=5){alert(lang==='es'?'Máximo 5 adjuntos por mensaje.':'Maximum 5 attachments per message.');break}if(file.size>10*1024*1024){alert(lang==='es'?'El límite es 10 MB por archivo.':'The limit is 10 MB per file.');continue}const entry={name:file.name,type:file.type,size:file.size};if(file.type.startsWith('image/')){try{entry.preview=await attachmentThumbnail(file)}catch{}}try{const saved=await storeAccountArtifact(file);if(authUser?.id!==owner)break;Object.assign(entry,saved);pendingAttachments.push(entry);refreshAttachments()}catch(error){alert(error.message)}}refreshAttachments()});attachmentUploadQueue=job.catch(()=>{});return job}
attachmentInput.onchange=()=>{const files=[...attachmentInput.files];attachmentInput.value='';return addAttachmentFiles(files)};

function chooseAttachment(type){attachmentMenu.hidden=true;attachmentButton.setAttribute('aria-expanded','false');attachmentInput.removeAttribute('capture');attachmentInput.multiple=true;attachmentInput.accept=type==='photo'?'image/*':type==='document'?'.pdf,.doc,.docx,.txt,.csv,.xls,.xlsx,.ppt,.pptx':type==='video'?'video/*,audio/*':'';if(type==='camera'){attachmentInput.accept='image/*';attachmentInput.setAttribute('capture','environment');attachmentInput.multiple=false}attachmentInput.click()}
attachmentButton.onclick=()=>{attachmentMenu.replaceChildren();[['photo',lang==='es'?'Fotos':'Photos'],['camera',lang==='es'?'Cámara':'Camera'],['document',lang==='es'?'Documentos':'Documents'],['video',lang==='es'?'Video y audio':'Video and audio'],['file',lang==='es'?'Otros archivos':'Other files']].forEach(([type,title])=>{const b=document.createElement('button');b.type='button';b.textContent=title;b.onclick=()=>chooseAttachment(type);attachmentMenu.append(b)});const note=document.createElement('small');note.textContent=lang==='es'?'En móvil, Cámara abre la captura si el dispositivo lo permite.':'On mobile, Camera opens capture when supported.';attachmentMenu.append(note);attachmentMenu.hidden=!attachmentMenu.hidden;attachmentButton.setAttribute('aria-expanded',String(!attachmentMenu.hidden))};document.addEventListener('click',e=>{if(!e.target.closest('#attachment-menu')&&!e.target.closest('#attach-open')){attachmentMenu.hidden=true;attachmentButton.setAttribute('aria-expanded','false')}});document.addEventListener('keydown',e=>{if(e.key==='Escape')attachmentMenu.hidden=true});
const sendWithoutAttachments=send;send=function(value){if(!pendingAttachments.length){sendWithoutAttachments(value);return}const files=[...pendingAttachments];const text=value.trim()||(lang==='es'?'Archivos adjuntos':'Attached files');const previousPending=pendingAttachments;pendingAttachments=[];try{sendWithoutAttachments(text);const chat=custom.find(c=>c.id===active);chat.attachments=chat.attachments||{};chat.attachments[chat.messages.length-2]=files;save();render();scrollBottom();refreshAttachments()}catch(e){pendingAttachments=previousPending;refreshAttachments();throw e}};
const originalInputUpdate=updateInput;updateInput=function(){originalInputUpdate();if(pendingAttachments.length)document.getElementById('send').disabled=false};document.getElementById('prompt').oninput=updateInput;const originalNewChat=newChat;newChat=function(){pendingAttachments=[];refreshAttachments();originalNewChat()};['new-chat','new-top'].forEach(id=>document.getElementById(id).onclick=newChat);
