(function(){
 const tr=(es,en)=>lang==='es'?es:en;
 let queue=Promise.resolve();
 async function request(path,options={},owner=authUser?.id){if(!owner||authUser?.id!==owner)throw Error("Account changed");const token=await authAccessToken();if(authUser?.id!==owner)throw Error("Account changed");const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error==='memory_changed'?tr('La memoria cambió en otro dispositivo. Vuelve a abrir esta sección.','Memory changed on another device. Reopen this section.'):tr('No se pudo completar. Vuelve a intentarlo.','Could not complete. Try again.'));return data;}
 async function panel(target){const owner=authUser?.id;target.replaceChildren();const h=document.createElement('h3');h.textContent=tr('Memoria y contexto','Memory and context');const status=document.createElement('p');status.setAttribute('role','status');target.append(h,status);if(!owner){status.textContent=tr('Inicia sesión para guardar tu memoria privada.','Sign in to save private memory.');return}status.textContent=tr('Cargando…','Loading…');try{const {memory}=await request('/api/memory');if(authUser?.id!==owner||!target.isConnected)return;status.textContent='';const form=document.createElement('form');form.className='memory-form';const add=(label,input)=>{const row=document.createElement('label');row.className='settings-field';const text=document.createElement('span');text.textContent=label;row.append(text,input);form.append(row)};
 const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=memory.enabled;add(tr('Usar mi perfil y memoria en texto y voz','Use my profile and memory in text and voice'),enabled);
 const learn=document.createElement('input');learn.type='checkbox';learn.checked=memory.learn;add(tr('Aprender mis preferencias al conversar','Learn my preferences while chatting'),learn);
 const note=document.createElement('p');note.textContent=tr('Se guarda en tu cuenta y se comparte con el modelo al responder. Solo aprende preferencias expresadas por ti; no guarda automáticamente datos sensibles. Desactivar la memoria impide usarla en nuevas respuestas. Reinicia una llamada activa después de cambiarla.','Saved in your account and shared with the model when answering. Only learns preferences you state; sensitive details are not saved automatically. Disable memory to stop using it in new replies. Restart an active call after changes.');form.append(note);
 const profile=document.createElement('textarea');profile.rows=4;profile.maxLength=1600;profile.value=memory.profile;add(tr('Sobre mí: nombre preferido, trabajo, gustos y objetivos','About me: preferred name, work, interests and goals'),profile);
 const notes=document.createElement('textarea');notes.rows=7;notes.maxLength=5000;notes.value=memory.notes.join('\n');add(tr('Lo que NUNA recuerda — un recuerdo por línea','What NUNA remembers — one memory per line'),notes);
 const heading=document.createElement('h4');heading.textContent=tr('Documentos que puede consultar','Documents it may consult');form.append(heading);const hint=document.createElement('p');hint.textContent=tr('Selecciona hasta 3 archivos de tu almacenamiento: PDF con texto, TXT, MD, CSV o JSON. Hasta 5 MB por archivo; lee las primeras 15 páginas de PDF y extractos de hasta 12.000 caracteres.','Select up to 3 stored files: text PDF, TXT, MD, CSV or JSON. Up to 5 MB per file; reads the first 15 PDF pages and excerpts up to 12,000 characters.');form.append(hint);const checks=[];try{const {files}=await request('/api/documents');if(authUser?.id!==owner)return;for(const file of files){const box=document.createElement('input');box.type='checkbox';box.checked=memory.documents.includes(file.id);checks.push([box,file.id]);add(file.name,box)}if(!files.length){const empty=document.createElement('p');empty.textContent=tr('Añade documentos en Almacenamiento para seleccionarlos aquí.','Add documents in Storage to select them here.');form.append(empty)}}catch{const error=document.createElement('p');error.textContent=tr('No se pudo cargar la lista de documentos.','Could not load the document list.');form.append(error)}
 const save=document.createElement('button');save.type='submit';save.textContent=tr('Guardar memoria','Save memory');const clear=document.createElement('button');clear.type='button';clear.className='danger';clear.textContent=tr('Borrar mi memoria','Delete my memory');form.append(save,clear);let revision=memory.updatedAt;
 form.onsubmit=async e=>{e.preventDefault();if(authUser?.id!==owner)return;const documents=checks.length?checks.filter(([c])=>c.checked).map(([,id])=>id):memory.documents;if(documents.length>3){status.textContent=tr('Selecciona hasta 3 documentos.','Select up to 3 documents.');return}save.disabled=true;try{const result=await request('/api/memory',{method:'PUT',body:JSON.stringify({expectedUpdatedAt:revision,memory:{enabled:enabled.checked,learn:learn.checked,profile:profile.value,notes:notes.value.split('\n').filter(Boolean),documents}})});if(authUser?.id!==owner)return;revision=result.memory.updatedAt;status.textContent=tr('Memoria guardada en tu cuenta.','Memory saved to your account.')}catch(error){status.textContent=error.message}finally{save.disabled=false}};
 clear.onclick=async()=>{if(!confirm(tr('¿Borrar perfil de memoria, recuerdos y acceso a documentos? Tus archivos y chats se conservan.','Delete memory profile, memories and document access? Files and chats are kept.')))return;if(authUser?.id!==owner)return;try{await request('/api/memory',{method:'PUT',body:JSON.stringify({expectedUpdatedAt:revision,memory:{enabled:false,learn:false,profile:'',notes:[],documents:[]}})});await panel(target)}catch(error){status.textContent=error.message}};target.append(form);
 }catch(error){status.textContent=error.message}}
 window.NunaMemory={panel,learn(text,owner=authUser?.id){if(!owner)return;queue=queue.catch(()=>{}).then(async()=>{if(authUser?.id!==owner)return;const result=await request('/api/memory',{method:'POST',body:JSON.stringify({text:String(text).slice(0,6000)})},owner);if(result.saved&&authUser?.id===owner){const notice=document.createElement('button');notice.className='memory-notice';notice.textContent=tr('Memoria actualizada · Ver','Memory updated · View');notice.onclick=()=>{settingsTab='memory';settingsMobileDetail=true;showSettings();settingsDialog.showModal()};document.querySelector('.composer-area').prepend(notice);setTimeout(()=>notice.remove(),9000)}}).catch(()=>{})},request};
 for(const [language,label]of [['es','Memoria'],['en','Memory']])settingsSections[language].splice(1,0,['memory',label]);
 const oldSettings=showSettings;showSettings=function(){oldSettings();if(settingsTab==='memory')panel(settingsDialog.querySelector('.settings-panel'))};
})();
