const aiCodeDialog=document.createElement('dialog');aiCodeDialog.id='ai-code-dialog';document.body.append(aiCodeDialog);
// A real password field (no autocapitalize/autocorrect) instead of prompt(): mobile keyboards can alter a code typed into prompt().
function askAICode(onCode){const es=lang==='es';aiCodeDialog.replaceChildren();const head=document.createElement('div');head.className='settings-head';const h=document.createElement('h2');h.textContent=es?'Probar IA':'Try AI';const close=document.createElement('button');close.type='button';close.className='icon';close.textContent='×';close.setAttribute('aria-label',es?'Cerrar':'Close');close.onclick=()=>aiCodeDialog.close();head.append(h,close);const form=document.createElement('form');form.className='auth-form';const label=document.createElement('label');label.className='settings-field';const span=document.createElement('span');span.textContent=es?'Código privado de prueba':'Private test code';const input=document.createElement('input');input.type='password';input.name='nuna-access-code';input.autocomplete='off';input.setAttribute('autocapitalize','off');input.setAttribute('autocorrect','off');input.spellcheck=false;input.required=true;label.append(span,input);const show=document.createElement('label');show.className='ai-code-show';const toggle=document.createElement('input');toggle.type='checkbox';toggle.onchange=()=>{input.type=toggle.checked?'text':'password'};show.append(toggle,document.createTextNode(es?' Mostrar código':' Show code'));const note=document.createElement('p');note.className='ai-code-note';note.textContent=es?'Es el valor de NUNA_ACCESS_CODE en Vercel, no tu clave de API. Se guarda solo en esta página y se borra al recargar.':'This is the NUNA_ACCESS_CODE value in Vercel, not your API key. It stays in this page only and is cleared on reload.';const submit=document.createElement('button');submit.type='submit';submit.className='auth-primary';submit.textContent=es?'Activar prueba':'Start test';form.append(label,show,note,submit);form.onsubmit=e=>{e.preventDefault();const code=input.value.trim();if(!code){input.focus();return}aiCodeDialog.close();onCode(code)};aiCodeDialog.append(head,form);aiCodeDialog.showModal();input.focus()}
let openAITestCode='',openAIBusy=false;
const aiProviders=['openai','anthropic','deepseek','gemini','grok','qwen'];
const aiErrors={provider_auth:['El proveedor rechazó la clave de API. Revisa que corresponda a este proveedor.','The provider rejected the API key. Check that it belongs to this provider.'],provider_permission:['El proveedor denegó el acceso. Revisa permisos y disponibilidad de API en tu cuenta o región.','The provider denied access. Check permissions and API availability for your account or region.'],provider_model:['El proveedor no encontró el modelo configurado. Revisa el identificador del modelo en Vercel.','The provider could not find the configured model. Check its ID in Vercel.'],provider_request:['El proveedor rechazó la solicitud. Revisa que el modelo sea compatible con esta API.','The provider rejected the request. Check model compatibility with this API.'],empty_response:['El proveedor respondió sin texto. Prueba un mensaje breve y revisa el modelo.','The provider returned no text. Try a brief message and check the model.'],provider_blocked:['El proveedor bloqueó esta solicitud. Prueba otra pregunta.','The provider blocked this request. Try another question.'],provider_output_limit:['Se agotó el límite de salida antes de obtener texto. Revisa la configuración del modelo.','The output limit was reached before text was generated. Check model settings.'],provider_timeout:['El proveedor tardó demasiado. Inténtalo de nuevo.','The provider took too long. Try again.'],access_code_missing:['El despliegue no tiene el código privado. Añade NUNA_ACCESS_CODE para Production y vuelve a desplegar.','This deployment has no private code. Add NUNA_ACCESS_CODE for Production and redeploy.'],access_code_short:['El código privado guardado en Vercel tiene menos de 16 caracteres. Amplíalo y vuelve a desplegar.','The private code saved in Vercel has fewer than 16 characters. Update it and redeploy.'],provider_key_missing:['Falta la clave de API del proveedor seleccionado en este despliegue. Revisa su variable para Production.','The selected provider API key is missing in this deployment. Check its Production variable.'],provider_model_missing:['Falta el identificador del modelo del proveedor seleccionado en este despliegue.','The selected provider model ID is missing in this deployment.'],not_configured:['Falta configurar la clave, el modelo o el código privado en Vercel.','Configure the provider key, model, and private code in Vercel.'],unauthorized:['El código de prueba no coincide con el configurado en este despliegue (NUNA_ACCESS_CODE). Pulsa «Probar IA» para escribirlo de nuevo.','The test code does not match the one configured for this deployment (NUNA_ACCESS_CODE). Press “Try AI” to enter it again.'],provider_limit:['El proveedor indicó un límite de uso. Revisa la cuota de API.','The provider reported a usage limit. Check your API quota.'],invalid_messages:['La conversación supera el límite de esta prueba. Inicia un chat nuevo.','This conversation exceeds the test limit. Start a new chat.']};
function aiErrorText(code){return(aiErrors[code]||['No se pudo obtener una respuesta del proveedor.','Could not get a provider reply.'])[lang==='es'?0:1]}
const aiKeyEnv={openai:'OPENAI_API_KEY',anthropic:'ANTHROPIC_API_KEY',deepseek:'DEEPSEEK_API_KEY',gemini:'GEMINI_API_KEY',grok:'XAI_API_KEY',qwen:'DASHSCOPE_API_KEY'};
const aiModelEnv={openai:'NUNA_OPENAI_MODEL',anthropic:'NUNA_ANTHROPIC_MODEL',deepseek:'NUNA_DEEPSEEK_MODEL',gemini:'NUNA_GEMINI_MODEL',grok:'NUNA_GROK_MODEL',qwen:'NUNA_QWEN_MODEL'};
// For a missing or unknown model, name the Vercel variable and the models the provider says this key can use.
function aiErrorMessage(data){const es=lang==='es';if(data?.error==='provider_key_missing'&&aiKeyEnv[data.provider]){const k=aiKeyEnv[data.provider];return es?'Este despliegue no tiene '+k+'. Añádela con ese nombre exacto en Vercel para el entorno que estás usando (Production para or-nuna.com, Preview para las vistas previas) y vuelve a desplegar.':'This deployment has no '+k+'. Add it with that exact name in Vercel for the environment you are using (Production for or-nuna.com, Preview for previews) and redeploy.'}const env=aiModelEnv[data?.provider];if(!env||!['provider_model','provider_model_missing'].includes(data.error))return aiErrorText(data?.error);const list=Array.isArray(data.available)?data.available.filter(n=>typeof n==='string').slice(0,12):[];const head=data.error==='provider_model'?(es?'El proveedor no encontró el modelo «'+String(data.model||'').slice(0,100)+'».':'The provider could not find the model “'+String(data.model||'').slice(0,100)+'”.'):(es?'Falta el modelo de este proveedor.':'This provider has no model set.');const options=list.length?(es?' Modelos disponibles para tu clave: ':' Models available to your key: ')+list.join(', ')+(data.available.length>list.length?'…':'')+'.':'';return head+options+(es?' Pon uno en '+env+' en Vercel (Production) y vuelve a desplegar.':' Set one in '+env+' in Vercel (Production) and redeploy.')}
// "Verificado" is recorded only after a real provider reply in this browser; server status only says whether a key and model are configured.
let aiVerified={},aiServerStatus=null;try{aiVerified=JSON.parse(localStorage.getItem('nuna-ai-verified')||'{}')||{}}catch{}
function saveAIVerified(){try{localStorage.setItem('nuna-ai-verified',JSON.stringify(aiVerified))}catch{}}
function markAIVerified(provider,model){aiVerified[provider]={at:new Date().toISOString(),model:typeof model==='string'?model.slice(0,80):''};if(aiServerStatus)aiServerStatus[provider]={key:true,model:true};saveAIVerified()}
// Errors about NUNA's own request (code, message limits) say nothing about the provider; any other failure means it is no longer verified.
const aiNonProviderErrors=['unauthorized','access_code_missing','access_code_short','invalid_messages','invalid_request','text_only','method_not_allowed','unsupported_provider'];
function noteAIFailure(provider,code){if(aiNonProviderErrors.includes(code)||!aiVerified[provider])return;delete aiVerified[provider];saveAIVerified()}
function aiConnectionError(){return new Error(lang==='es'?'No se pudo conectar. Comprueba la configuración y vuelve a intentar.':'Connection failed. Check configuration and try again.')}
async function aiFetch(url,options){try{return await fetch(url,options)}catch{throw aiConnectionError()}}
function aiStatus(provider){const es=lang==='es';if(!aiProviders.includes(provider))return{text:es?'Sin integración':'No integration',kind:'none'};const server=aiServerStatus?.[provider];if(server&&!server.key)return{text:es?'Falta clave':'Key missing',kind:'missing'};if(server&&!server.model)return{text:es?'Falta modelo':'Model missing',kind:'missing'};if(aiVerified[provider])return{text:es?'Verificado':'Verified',kind:'ok'};if(server)return{text:es?'Configurado · sin verificar':'Configured · not verified',kind:'configured'};return{text:es?'Sin comprobar':'Not checked',kind:'unknown'}}
async function fetchAIStatus(){const response=await aiFetch('/api/chat',{headers:{'x-nuna-access-code':openAITestCode},signal:AbortSignal.timeout(15000)});const data=await response.json().catch(()=>({}));if(!response.ok){if(data.error==='unauthorized')openAITestCode='';throw new Error(aiErrorMessage(data))}aiServerStatus=data.providers||null;return aiServerStatus}
async function testAIConnection(provider){const response=await aiFetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','x-nuna-access-code':openAITestCode},body:JSON.stringify({provider,messages:[{role:'user',content:'Responde solo con la palabra OK.'}]}),signal:AbortSignal.timeout(55000)});const data=await response.json().catch(()=>({}));if(!response.ok){if(data.error==='unauthorized')openAITestCode='';noteAIFailure(provider,data.error);throw new Error(aiErrorMessage(data))}if(typeof data.text!=='string'||!data.text.trim()){noteAIFailure(provider,'empty_response');throw new Error(aiErrorText('empty_response'))}markAIVerified(provider,data.model);return data}
// Ask for the private code only when none is active; resolves with whether a code is now available.
function ensureAICode(){return new Promise(resolve=>{if(openAITestCode){resolve(true);return}let done=false;const finish=v=>{if(!done){done=true;resolve(v)}};aiCodeDialog.addEventListener('close',()=>setTimeout(()=>finish(Boolean(openAITestCode)),0),{once:true});askAICode(code=>{openAITestCode=code;refreshOpenAITest();finish(true)})})}
const sendDemo=send;const openAIControl=document.createElement('button');openAIControl.type='button';openAIControl.id='openai-test';document.querySelector('.header-actions').prepend(openAIControl);const openAIStatus=document.createElement('p');openAIStatus.id='openai-status';openAIStatus.setAttribute('role','status');document.querySelector('.composer-area').prepend(openAIStatus);
function refreshOpenAITest(){openAIControl.textContent=openAITestCode?(lang==='es'?'Salir de prueba IA':'Exit AI test'):(lang==='es'?'Probar IA':'Try AI');document.querySelector('.disclaimer').textContent=openAITestCode?(lang==='es'?'Prueba privada: los mensajes enviados al proveedor seleccionado pueden consumir crédito de API.':'Private test: messages sent to the selected provider may consume API credit.') :strings[lang].disclaimer;document.getElementById('send').disabled=openAIBusy||(!document.getElementById('prompt').value.trim()&&!pendingAttachments.length);if(typeof refreshAIMode==='function')refreshAIMode()}
openAIControl.onclick=()=>{if(openAIBusy)return;if(openAITestCode){openAITestCode='';openAIStatus.textContent='';refreshOpenAITest();return}askAICode(code=>{openAITestCode=code;if(!['openai','anthropic','deepseek','gemini','grok','qwen'].includes(preferredModel))preferredModel='openai';saveModels();updateModelLabel();openAIStatus.textContent=lang==='es'?'Modo de prueba IA: OpenAI, Anthropic, DeepSeek, Gemini, Grok o Qwen. Solo texto. El código se validará al enviar un mensaje.':'AI test mode: OpenAI, Anthropic, DeepSeek, Gemini, Grok, or Qwen. Text only. Your code will be checked when you send a message.';refreshOpenAITest()})};
const aiDemoHint=document.createElement('div');aiDemoHint.id='ai-demo-hint';const aiDemoText=document.createElement('span');const aiDemoButton=document.createElement('button');aiDemoButton.type='button';aiDemoButton.onclick=()=>{if(!openAITestCode)openAIControl.click()};aiDemoHint.append(aiDemoText,aiDemoButton);openAIStatus.after(aiDemoHint);
// Without the private code, replies are simulated: say so next to the composer and offer the real test for the selected provider.
function refreshAIMode(){const es=lang==='es';const real=aiProviders.includes(preferredModel);aiDemoHint.hidden=Boolean(openAITestCode);aiDemoText.textContent=es?'Modo demostración: las respuestas son simuladas.':'Demo mode: replies are simulated.';const name=(models.find(m=>m.id===preferredModel)||{}).name||'';aiDemoButton.hidden=!real;aiDemoButton.textContent=es?'Usar '+name+' real':'Use real '+name;const badge=document.querySelector('.header-left .badge');if(badge)badge.textContent=openAITestCode?(es?'PRUEBA REAL':'REAL TEST'):strings[lang].prototype}
const uiRender=render;render=function(){uiRender();refreshOpenAITest()};
send=async function(value){if(openAIBusy)return;if(!openAITestCode){sendDemo(value);return}if(!['openai','anthropic','deepseek','gemini','grok','qwen'].includes(preferredModel)){openAIStatus.textContent=lang==='es'?'Selecciona OpenAI, Anthropic, DeepSeek, Gemini, Grok o Qwen para la prueba real o sal del modo de prueba.':'Select OpenAI, Anthropic, DeepSeek, Gemini, Grok, or Qwen for the real test or exit test mode.';return}if(pendingAttachments.length){openAIStatus.textContent=lang==='es'?'La prueba real admite solo texto. Quita los adjuntos antes de enviar.':'The real test supports text only. Remove attachments before sending.';return}const text=value.trim();if(!text)return;let chat=custom.find(c=>c.id===active);if(!chat){const example=examples.find(c=>c.id===active);chat={id:crypto.randomUUID(),title:example?example.title[lang]:text.slice(0,45),messages:example?example.messages[lang].map(m=>[...m]):[],project:currentProject};custom.unshift(chat);active=chat.id}chat.messages.push(['user',text]);document.getElementById('prompt').value='';save();openAIBusy=true;render();scrollBottom();openAIStatus.textContent=lang==='es'?'El modelo está preparando una respuesta…':'The model is preparing a reply…';try{const aiProvider=preferredModel;const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','x-nuna-access-code':openAITestCode},body:JSON.stringify({provider:aiProvider,messages:chat.messages.slice(-30).map(([role,content])=>({role,content}))}),signal:AbortSignal.timeout(55000)});const data=await response.json();if(!response.ok){if(data.error==='unauthorized')openAITestCode='';noteAIFailure(aiProvider,data.error);throw new Error(aiErrorMessage(data))}if(typeof data.text!=='string'||!data.text.trim())throw Error(lang==='es'?'Respuesta vacía.':'Empty response.');chat.messages.push(['assistant',data.text]);save();markAIVerified(aiProvider,data.model);openAIStatus.textContent=lang==='es'?'Respuesta del modelo recibida.':'Model reply received.';}catch(e){openAIStatus.textContent=(e.name==='TimeoutError'||e.name==='TypeError')?(lang==='es'?'No se pudo conectar. Comprueba la configuración y vuelve a intentar.':'Connection failed. Check configuration and try again.'):e.message; // Keep failed input as a draft; do not create a fake assistant reply.
if(chat.messages.at(-1)?.[0]==='user'&&chat.messages.at(-1)?.[1]===text){chat.messages.pop();save()}if(active===chat.id)document.getElementById('prompt').value=text;}finally{openAIBusy=false;render();if(active===chat.id)scrollBottom()}};
const aiLanguageObserver=new MutationObserver(refreshOpenAITest);aiLanguageObserver.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});refreshOpenAITest();
