let profilePhoto='',profilePhotoOwner=null,profilePhotoLoading=null;
function paintProfilePhoto(){
 const usable=authUser?.id===profilePhotoOwner&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(profilePhoto);
 document.querySelectorAll('.avatar,.settings-profile-avatar').forEach(el=>{el.replaceChildren();if(usable){const img=document.createElement('img');img.src=profilePhoto;img.alt=lang==='es'?'Foto de perfil':'Profile photo';el.append(img);}else el.textContent=profileName?profileName[0].toUpperCase():'T';});
 const upload=document.getElementById('profile-photo-upload');if(upload)upload.textContent=lang==='es'?(usable?'Cambiar foto':'Subir foto'):(usable?'Change photo':'Upload photo');const remove=document.getElementById('profile-photo-remove');if(remove)remove.hidden=!usable;
}
async function loadProfilePhoto(force=false){
 const owner=authUser?.id||null;if(!owner){profilePhoto='';profilePhotoOwner=null;paintProfilePhoto();return;}
 if(!authClient||profilePhotoLoading===owner||(!force&&profilePhotoOwner===owner))return;
 profilePhoto='';profilePhotoOwner=null;profilePhotoLoading=owner;paintProfilePhoto();
 const {data,error}=await authClient.from('profile_photos').select('photo').eq('owner',owner).maybeSingle();if(authUser?.id!==owner){profilePhotoLoading=null;return;}
 profilePhotoLoading=null;if(!error){profilePhotoOwner=owner;profilePhoto=data?.photo||'';paintProfilePhoto();}
}
const updateProfileBeforePhoto=updateProfile;updateProfile=function(){updateProfileBeforePhoto();if((authUser?.id||null)!==profilePhotoOwner)loadProfilePhoto();paintProfilePhoto();};
const showSettingsBeforePhoto=showSettings;showSettings=function(){
 showSettingsBeforePhoto();if(settingsTab!=='profile')return;const panel=settingsDialog.querySelector('.settings-panel'),avatar=panel.querySelector('.settings-profile-avatar');if(!avatar)return;
 const controls=document.createElement('div');controls.className='profile-photo-controls';const status=document.createElement('p');status.className='settings-note';status.setAttribute('role','status');const upload=document.createElement('button');upload.id='profile-photo-upload';upload.type='button';const remove=document.createElement('button');remove.id='profile-photo-remove';remove.type='button';remove.textContent=lang==='es'?'Quitar foto':'Remove photo';const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.hidden=true;
 controls.append(upload,remove,input);avatar.after(controls,status);loadProfilePhoto();paintProfilePhoto();
 const nameInput=panel.querySelector('.settings-field input');if(nameInput){const original=nameInput.oninput;nameInput.oninput=e=>{original?.(e);paintProfilePhoto();};}
 const oldNote=[...panel.querySelectorAll('p')].find(p=>/El avatar usa la inicial|Your avatar uses/.test(p.textContent));if(oldNote)oldNote.textContent=lang==='es'?'Tu foto se guarda en tu cuenta y aparece al iniciar sesión en otros dispositivos.':'Your photo is saved to your account and appears when you sign in on other devices.';
 const say=(es,en)=>status.textContent=lang==='es'?es:en;
 async function storePhoto(photo){const owner=authUser?.id;if(!owner||!cloudMode()){say('Inicia sesión para guardar tu foto.','Sign in to save your photo.');return false;}upload.disabled=remove.disabled=true;const {error}=await authClient.from('profile_photos').upsert({owner,photo,updated_at:new Date().toISOString()},{onConflict:'owner'});upload.disabled=remove.disabled=false;if(error){say('No se pudo guardar la foto. Inténtalo de nuevo.','Could not save the photo. Try again.');return false;}if(authUser?.id!==owner)return false;profilePhotoOwner=owner;profilePhoto=photo;paintProfilePhoto();say(photo?'Foto guardada en tu cuenta.':'Foto quitada.',photo?'Photo saved to your account.':'Photo removed.');return true;}
 upload.onclick=()=>{if(!authUser){say('Inicia sesión para guardar tu foto.','Sign in to save your photo.');return;}input.click();};remove.onclick=()=>storePhoto('');
 input.onchange=async()=>{const file=input.files?.[0];input.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){say('Elige una imagen JPG, PNG o WebP de hasta 5 MB.','Choose a JPG, PNG or WebP image up to 5 MB.');return;}try{const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error();}const canvas=document.createElement('canvas');canvas.width=canvas.height=240;const context=canvas.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,240,240);const side=Math.min(bitmap.width,bitmap.height);context.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,240,240);bitmap.close();let data=canvas.toDataURL('image/jpeg',.8);if(data.length>120000)data=canvas.toDataURL('image/jpeg',.5);await storePhoto(data);}catch{say('No se pudo abrir esa imagen. Prueba con otra.','Could not open that image. Try another.');}};
};
const profilePhotoStyle=document.createElement('style');profilePhotoStyle.textContent='.avatar,.settings-profile-avatar{overflow:hidden}.avatar img,.settings-profile-avatar img{width:100%;height:100%;object-fit:cover;display:block}.profile-photo-controls{display:flex;gap:8px;margin:-15px 0 8px}.profile-photo-controls button{padding:8px 12px;border:1px solid var(--border);border-radius:9px;background:var(--side);color:var(--text);font-size:12px}.profile-photo-controls button[hidden]{display:none}.profile-photo-controls button:disabled{opacity:.5}';document.head.append(profilePhotoStyle);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')loadProfilePhoto(true);});updateProfile();
