// Account security uses Supabase's WebAuthn ceremonies, never a locally stored PIN.
function securityText(es,en){return lang==='es'?es:en}
function passkeySupported(){return window.isSecureContext&&typeof window.PublicKeyCredential!=='undefined'&&Boolean(navigator.credentials)}
function securityError(error){
 const code=String(error?.code||'');
 if(code==='passkey_disabled')return securityText('Las llaves de acceso todavía no están habilitadas. Usa Google o contraseña.','Passkeys are not enabled yet. Use Google or password.');
 if(error?.name==='NotAllowedError'||/cancel|timed out/i.test(error?.message||''))return securityText('Operación cancelada o tiempo agotado. Puedes intentarlo de nuevo.','Cancelled or timed out. You can try again.');
 if(code==='webauthn_credential_exists')return securityText('Esta llave ya está registrada.','This passkey is already registered.');
 if(code==='webauthn_credential_not_found')return securityText('No se encontró una llave para NUNA en este dispositivo. Usa otro método.','No NUNA passkey was found on this device. Use another method.');
 return authErrorText(error);
}
function renderSecuritySettings(panel){
 const t=securityText, es=lang==='es';
 function note(text){const p=document.createElement('p');p.textContent=text;panel.append(p);return p}
 function action(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b}
 const status=note('');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 if(!authUser||!authClient){note(t('Inicia sesión para gestionar la seguridad de tu cuenta.','Sign in to manage your account security.'));panel.append(action(t('Iniciar sesión','Sign in'),()=>{settingsDialog.close();openAuth('login')}));return}
 note(authUser.email||'');
 const methods=document.createElement('section');methods.className='security-block';
 const title=document.createElement('h4');title.textContent=t('Acceso a tu cuenta','Account sign-in');methods.append(title);
 const password=action(t('Cambiar o crear contraseña','Change or create password'),()=>{settingsDialog.close();openAuth('recovery')});methods.append(password);
 const google=document.createElement('p');const linked=authUser.identities?.some(i=>i.provider==='google');google.textContent=linked?t('Google está conectado a esta cuenta.','Google is connected to this account.'):t('Google está disponible en el formulario de acceso. Usa el método de tu cuenta.','Google is available on the sign-in form. Use your account’s sign-in method.');methods.append(google);panel.append(methods);
 const block=document.createElement('section');block.className='security-block';const heading=document.createElement('h4');heading.textContent=t('Llaves de acceso','Passkeys');block.append(heading);
 const description=document.createElement('p');description.textContent=t('Usa Face ID, Touch ID, el PIN de tu dispositivo o un gestor como Google. Tu dispositivo elige el método; NUNA no recibe tu rostro ni tu PIN.','Use Face ID, Touch ID, your device PIN, or a manager such as Google. Your device chooses the method; NUNA never receives your face or PIN.');block.append(description);
 const list=document.createElement('div');list.className='security-keys';const add=action(t('Añadir llave de acceso','Add passkey'),async()=>{add.disabled=true;status.textContent=t('Sigue la indicación de tu dispositivo.','Follow your device’s prompt.');try{const {error}=await authClient.auth.registerPasskey();if(error)throw error;status.textContent=t('Llave de acceso añadida.','Passkey added.');await loadKeys()}catch(e){status.textContent=securityError(e)}finally{add.disabled=!passkeySupported()}});
 block.append(add,list);panel.append(block);
 if(!passkeySupported()){add.disabled=true;note(t('Este navegador no admite llaves de acceso. Puedes usar Google o contraseña.','This browser does not support passkeys. You can use Google or password.'))}
 async function loadKeys(){
  list.replaceChildren();const loading=document.createElement('p');loading.textContent=t('Cargando llaves…','Loading passkeys…');list.append(loading);
  try{const {data,error}=await authClient.auth.passkey.list();if(error)throw error;if(!panel.isConnected)return;list.replaceChildren();if(!data?.length){const empty=document.createElement('p');empty.textContent=t('Todavía no has añadido una llave.','You have not added a passkey yet.');list.append(empty);return}
   for(const key of data){const row=document.createElement('div');row.className='security-key';const name=document.createElement('strong');name.textContent=key.friendly_name||t('Llave de acceso','Passkey');row.append(name);
    const rename=action(t('Editar nombre','Rename'),()=>{const form=document.createElement('form');const input=document.createElement('input');input.type='text';input.maxLength=120;input.required=true;input.value=key.friendly_name||'';input.setAttribute('aria-label',t('Nombre de la llave','Passkey name'));const save=action(t('Guardar','Save'),()=>{});save.type='submit';save.onclick=null;const cancel=action(t('Cancelar','Cancel'),()=>loadKeys());form.append(input,save,cancel);row.replaceChildren(form);input.focus();form.onsubmit=async e=>{e.preventDefault();if(!input.value.trim())return;save.disabled=true;const {error}=await authClient.auth.passkey.update({passkeyId:key.id,friendlyName:input.value.trim()});if(error){status.textContent=securityError(error);save.disabled=false}else{status.textContent=t('Nombre actualizado.','Name updated.');await loadKeys()}}});
    const remove=action(t('Quitar','Remove'),()=>{const confirm=document.createElement('div');confirm.className='security-confirm';const text=document.createElement('p');text.textContent=t('¿Quitar esta llave? Comprueba que puedes entrar con Google o contraseña.','Remove this passkey? Make sure you can sign in with Google or password.');const yes=action(t('Sí, quitar llave','Yes, remove passkey'),async()=>{yes.disabled=true;const {error}=await authClient.auth.passkey.delete({passkeyId:key.id});if(error){status.textContent=securityError(error);yes.disabled=false}else{status.textContent=t('Llave eliminada.','Passkey removed.');await loadKeys()}});confirm.append(text,yes,action(t('Cancelar','Cancel'),()=>loadKeys()));row.replaceChildren(confirm)});row.append(rename,remove);list.append(row)}
  }catch(e){loading.textContent=securityError(e)}
 }
 loadKeys();
 const sessions=document.createElement('section');sessions.className='security-block';const sh=document.createElement('h4');sh.textContent=t('Sesiones','Sessions');sessions.append(sh);
 const sessionNote=document.createElement('p');sessionNote.textContent=t('Cerrar las otras sesiones mantiene abierto este dispositivo. Las sesiones cerradas pueden conservar acceso hasta que expire su token actual.','Closing other sessions keeps this device signed in. Signed-out sessions may retain access until their current token expires.');sessions.append(sessionNote);
 sessions.append(action(t('Cerrar otras sesiones','Sign out other sessions'),()=>{const box=document.createElement('div');box.className='security-confirm';const text=document.createElement('p');text.textContent=t('¿Cerrar las otras sesiones de tu cuenta?','Sign out your other account sessions?');const yes=action(t('Confirmar','Confirm'),async()=>{yes.disabled=true;const {error}=await authClient.auth.signOut({scope:'others'});if(error){status.textContent=authErrorText(error);yes.disabled=false}else{status.textContent=t('Otras sesiones cerradas. Este dispositivo sigue conectado.','Other sessions signed out. This device remains signed in.');box.remove()}});box.append(text,yes,action(t('Cancelar','Cancel'),()=>box.remove()));sessions.append(box)}));panel.append(sessions);
}
const securityStyle=document.createElement('style');securityStyle.textContent='.security-block{border-top:1px solid var(--border);padding:20px 0}.security-block h4{font-size:17px;font-weight:500;margin:0 0 12px}.security-key{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin:14px 0}.security-key strong{flex:1;min-width:130px;font-size:14px;font-weight:500}.security-key form{display:flex;gap:8px;flex-wrap:wrap;width:100%}.security-key input{padding:10px;border:1px solid var(--border);border-radius:10px;background:var(--bg);color:var(--text);min-width:0;max-width:100%}.security-confirm{width:100%}.security-confirm button{margin:0 8px 8px 0}.security-block button:disabled{opacity:.5;cursor:default}';document.head.append(securityStyle);
