(async()=>{
 const box=document.getElementById('messages'),token=location.hash.slice(1);history.replaceState(null,'',location.pathname+'#'+token);
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(token)){box.textContent='Este enlace no es válido.';return;}
 try{
 const config=await fetch('/api/config').then(r=>r.json());if(!config.supabase)throw Error();
 const r=await fetch(config.supabase.url+'/rest/v1/shared_conversations?id=eq.'+encodeURIComponent(token)+'&select=title,messages',{headers:{apikey:config.supabase.key,'x-nuna-share':token},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();const rows=await r.json();
 if(!rows.length){box.textContent='Este enlace fue desactivado o no existe.';return;}
 document.getElementById('title').textContent=rows[0].title;box.replaceChildren();box.removeAttribute('role');
 for(const message of rows[0].messages){if(!Array.isArray(message)||!['user','assistant'].includes(message[0])||typeof message[1]!=='string')continue;const article=document.createElement('article');article.className='message '+message[0];const role=document.createElement('strong');role.textContent=message[0]==='user'?'Usuario':'NUNA AI';const content=document.createElement('div');content.textContent=message[1];article.append(role,content);box.append(article);}
 await addSharedComments(config,token).catch(()=>{});
 }catch{box.textContent='No se pudo abrir la conversación. Inténtalo de nuevo.';}
})();

async function addSharedComments(config,token){
 const section=document.createElement('section');section.className='shared-comments';const h=document.createElement('h2');h.textContent='Comentarios';const note=document.createElement('p');note.className='notice';note.textContent='Los comentarios son independientes y no alteran el chat original.';const list=document.createElement('div');const status=document.createElement('p');status.setAttribute('role','status');section.append(h,note,list,status);document.querySelector('main').append(section);
 const headers={apikey:config.supabase.key,'x-nuna-share':token};
 async function load(){try{const r=await fetch(config.supabase.url+'/rest/v1/share_comments?share_id=eq.'+encodeURIComponent(token)+'&select=author_name,body,created_at&order=created_at.asc&limit=200',{headers,cache:'no-store'});if(!r.ok)throw Error();const comments=await r.json();list.replaceChildren();for(const c of comments){const article=document.createElement('article');article.className='message';const name=document.createElement('strong');name.textContent=c.author_name;const text=document.createElement('div');text.textContent=c.body;article.append(name,text);list.append(article);}if(!comments.length)list.textContent='Todavía no hay comentarios.';}catch{status.textContent='No se pudieron cargar los comentarios.';}}
 await load();
 await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/dist/umd/supabase.js';script.integrity='sha384-Rj26LVGvoeRVR6+mwQmFfcR3QOBEwT+ZmuCWpuiqeTzJpCs0ER4ITAWGb4Hiy3Ok';script.crossOrigin='anonymous';script.onload=resolve;script.onerror=reject;document.head.append(script);});
 const client=window.supabase.createClient(config.supabase.url,config.supabase.key,{auth:{storageKey:'nuna-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false},global:{headers:{'x-nuna-share':token}}});const controls=document.createElement('div');section.append(controls);
 let formUserId;async function showForm(){const {data}=await client.auth.getSession();const userId=data.session?.user.id||null;if(formUserId===userId&&controls.childNodes.length)return;formUserId=userId;controls.replaceChildren();if(!data.session){const sign=document.createElement('a');sign.href='/?login=1';sign.target='_blank';sign.rel='noopener';sign.textContent='Inicia sesión en NUNA para comentar';const hint=document.createElement('p');hint.className='notice';hint.textContent='Después vuelve a esta página. El enlace sigue siendo de solo lectura.';controls.append(sign,hint);return;}
 const form=document.createElement('form');const input=document.createElement('textarea');input.maxLength=2000;input.required=true;input.rows=3;input.placeholder='Añade un comentario…';input.setAttribute('aria-label','Comentario');const submit=document.createElement('button');submit.textContent='Publicar comentario';form.append(input,submit);controls.append(form);
 form.onsubmit=async e=>{e.preventDefault();const body=input.value.trim();if(!body)return;submit.disabled=true;const {data:current}=await client.auth.getUser();if(!current.user){status.textContent='Inicia sesión para comentar.';submit.disabled=false;return;}const name=String(current.user.user_metadata?.full_name||current.user.user_metadata?.name||'Lector').trim().slice(0,60)||'Lector';const {error}=await client.from('share_comments').insert({share_id:token,author:current.user.id,author_name:name,body});submit.disabled=false;if(error){status.textContent='No se pudo publicar. El enlace puede haberse desactivado.';return;}input.value='';status.textContent='Comentario publicado.';await load();};}
 await showForm();window.addEventListener('focus',()=>{showForm();load();});
}
