// Private account files. Generators call NunaArtifacts.store with their returned bytes.
const artifactCategories=['photos','videos','documents','audio','other'];
function artifactCategory(file){const type=(file.type||'').toLowerCase(),name=(file.name||'').toLowerCase();if(type.startsWith('image/')||/\.(png|jpe?g|webp|gif|heic|avif|svg)$/.test(name))return'photos';if(type.startsWith('video/')||/\.(mp4|mov|webm|mkv|avi)$/.test(name))return'videos';if(type.startsWith('audio/')||/\.(mp3|wav|m4a|ogg|flac)$/.test(name))return'audio';if(/\.(pdf|docx?|xlsx?|pptx?|txt|csv|md|rtf|odt|ods|json)$/.test(name)||type.startsWith('text/')||type==='application/pdf')return'documents';return'other'}
function fileBytes(bytes){return bytes<1024?bytes+' B':bytes<1048576?(bytes/1024).toFixed(1)+' KB':(bytes/1048576).toFixed(1)+' MB'}
async function storeAccountArtifact(file){
 const owner=authUser?.id;if(!owner||!authClient)throw Error(lang==='es'?'Inicia sesión para guardar archivos en tu cuenta.':'Sign in to save files to your account.');if(!(file instanceof Blob)||!file.size||file.size>10485760)throw Error(lang==='es'?'Usa archivos de entre 1 byte y 10 MB.':'Use files between 1 byte and 10 MB.');
 const category=artifactCategory(file),name=(file.name||'archivo').normalize('NFKC').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-140)||'archivo';const path=owner+'/'+category+'/'+crypto.randomUUID()+'--'+name;
 const {error}=await authClient.storage.from('nuna-files').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(error)throw Error(lang==='es'?'No se pudo guardar el archivo. Comprueba la conexión e inténtalo de nuevo.':'Could not save the file. Check your connection and try again.');
 if(authUser?.id!==owner)throw Error(lang==='es'?'La cuenta cambió durante la carga. El archivo quedó en la cuenta original.':'The account changed during upload. The file stays in the original account.');
 return {name:file.name||name,size:file.size,type:file.type,category,path,owner};
}
window.NunaArtifacts={store:storeAccountArtifact};
async function accountFileList(owner,category){let entries=[];for(let offset=0;;offset+=100){const {data,error}=await authClient.storage.from('nuna-files').list(owner+'/'+category,{limit:100,offset,sortBy:{column:'created_at',order:'desc'}});if(error)throw error;entries.push(...(data||[]).filter(x=>x.id));if(!data||data.length<100)break;if(offset>=9900)break}return entries}
function renderAccountStorage(panel){
 const es=lang==='es',t=(a,b)=>es?a:b,owner=authUser?.id;const status=document.createElement('p');status.setAttribute('role','status');panel.append(status);
 if(!owner||!authClient){status.textContent=t('Inicia sesión para ver tus archivos guardados.','Sign in to see your saved files.');const login=document.createElement('button');login.textContent=t('Iniciar sesión','Sign in');login.onclick=()=>{settingsDialog.close();openAuth('login')};panel.append(login);return}
 const summary=document.createElement('div');summary.className='storage-summary';const caption=document.createElement('span');caption.textContent=t('Archivos privados de tu cuenta','Private files in your account');const bytes=document.createElement('strong');bytes.textContent='…';summary.append(caption,bytes);panel.append(summary);
 const upload=document.createElement('button');upload.textContent=t('Añadir archivos','Add files');upload.type='button';const input=document.createElement('input');input.type='file';input.multiple=true;input.hidden=true;upload.onclick=()=>input.click();input.onchange=async()=>{const files=[...input.files];input.value='';upload.disabled=true;let stored=0,failed=0;for(const file of files){try{await storeAccountArtifact(file);stored++}catch{failed++}}status.textContent=t(`${stored} archivos guardados${failed?`; ${failed} no se pudieron guardar (máximo 10 MB por archivo)`:''}.`,`${stored} files saved${failed?`; ${failed} could not be saved (10 MB maximum per file)`:''}.`);upload.disabled=false;await refresh()};panel.append(upload,input);
 const grid=document.createElement('div');grid.className='storage-grid';panel.append(grid);const details=document.createElement('div');details.className='storage-detail';details.hidden=true;panel.append(details);
 const note=document.createElement('p');note.className='settings-note';note.textContent=t('Los archivos se clasifican automáticamente. Chats y proyectos conservan sus categorías. Las fotos locales antiguas de Work no se trasladan automáticamente. Guardar un archivo no lo envía a la IA.','Files are categorized automatically. Chats and projects keep their categories. Older local Work photos are not automatically moved. Saving a file does not send it to the AI.');panel.append(note);
 let categories={};const labels={photos:t('Fotos','Photos'),videos:t('Videos','Videos'),documents:t('Documentos','Documents'),audio:t('Audio','Audio'),other:t('Otros archivos','Other files'),chats:t('Chats','Chats'),projects:t('Proyectos','Projects')};
 async function refresh(){try{const data=await Promise.all(artifactCategories.map(async c=>[c,await accountFileList(owner,c)]));if(authUser?.id!==owner||!panel.isConnected)return;categories=Object.fromEntries(data);let total=0;grid.replaceChildren();for(const c of [...artifactCategories,'chats','projects']){const entries=c==='chats'?custom:c==='projects'?projects:categories[c];const size=c==='chats'||c==='projects'?new Blob([JSON.stringify(entries)]).size:entries.reduce((s,f)=>s+Number(f.metadata?.size||0),0);if(artifactCategories.includes(c))total+=size;const card=document.createElement('button');card.type='button';card.className='storage-category';const title=document.createElement('strong');title.textContent=labels[c];const count=document.createElement('span');count.textContent=entries.length+' '+t('elementos','items')+' · '+fileBytes(size);card.append(title,count);card.onclick=()=>showCategory(c);grid.append(card)}bytes.textContent=fileBytes(total)}catch{status.textContent=t('No se pudieron cargar tus archivos. Vuelve a abrir Almacenamiento para reintentar.','Could not load your files. Reopen Storage to try again.');bytes.textContent='—'}}
 function showCategory(category){details.hidden=false;details.replaceChildren();const h=document.createElement('h4');h.textContent=labels[category];details.append(h);const files=category==='chats'?custom:category==='projects'?projects:categories[category];if(!files.length){const p=document.createElement('p');p.textContent=t('Todavía no hay elementos en esta categoría.','No items in this category yet.');details.append(p)}
 for(const file of files){const row=document.createElement('div');row.className='storage-item';const name=document.createElement('span');name.textContent=category==='chats'?(typeof file.title==='string'?file.title:file.title?.[lang]||t('Chat','Chat')):category==='projects'?file.name:file.name.replace(/^[a-f0-9-]{36}--/,'');row.append(name);
 if(artifactCategories.includes(category)){const open=document.createElement('button');open.type='button';open.textContent=t('Descargar','Download');open.onclick=async()=>{open.disabled=true;try{if(authUser?.id!==owner)throw Error();const {data,error}=await authClient.storage.from('nuna-files').download(owner+'/'+category+'/'+file.name);if(error)throw error;const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name.textContent;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{status.textContent=t('No se pudo descargar el archivo.','Could not download the file.')}finally{open.disabled=false}};row.append(open)}else if(category==='chats'){const open=document.createElement('button');open.textContent=t('Abrir chat','Open chat');open.onclick=()=>{active=file.id;settingsDialog.close();render();scrollBottom()};row.append(open)}details.append(row)}details.scrollIntoView({block:'nearest'})}
 refresh();
}
const artifactStyle=document.createElement('style');artifactStyle.textContent='.storage-item{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.storage-item>span{flex:1;min-width:130px;overflow-wrap:anywhere}.storage-item button{flex-shrink:0}';document.head.append(artifactStyle);
