// Private account files. Generators call NunaArtifacts.store with their returned bytes.
const accountStorageEndpoint='https://nuna-private-storage.nuna-security.workers.dev';
async function accountStorageRequest(path,options={},owner=authUser?.id){
 if(!owner||authUser?.id!==owner||!authClient)throw Error(lang==='es'?'Inicia sesión para usar tu almacenamiento.':'Sign in to use your storage.');
 const {data,error}=await authClient.auth.getSession();
 if(error||!data?.session?.access_token||authUser?.id!==owner)throw Error(lang==='es'?'Vuelve a iniciar sesión.':'Please sign in again.');
 const headers=new Headers(options.headers);headers.set('Authorization','Bearer '+data.session.access_token);
 const response=await fetch(accountStorageEndpoint+path,{...options,headers});
 if(!response.ok){const result=await response.json().catch(()=>({}));throw Error(result.error==='quota_exceeded'?(lang==='es'?'Alcanzaste tus 15 GB de almacenamiento.':'You reached your 15 GB storage allowance.'):(lang==='es'?'No se pudo completar la operación de almacenamiento.':'The storage operation could not be completed.'));}
 if(authUser?.id!==owner)throw Error(lang==='es'?'La cuenta cambió durante la operación.':'The account changed during the operation.');
 return response;
}
const artifactCategories=['photos','videos','documents','audio','other'];
function artifactCategory(file){const type=(file.type||'').toLowerCase(),name=(file.name||'').toLowerCase();if(type.startsWith('image/')||/\.(png|jpe?g|webp|gif|heic|avif|svg)$/.test(name))return'photos';if(type.startsWith('video/')||/\.(mp4|mov|webm|mkv|avi)$/.test(name))return'videos';if(type.startsWith('audio/')||/\.(mp3|wav|m4a|ogg|flac)$/.test(name))return'audio';if(/\.(pdf|docx?|xlsx?|pptx?|txt|csv|md|rtf|odt|ods|json)$/.test(name)||type.startsWith('text/')||type==='application/pdf')return'documents';return'other'}
function fileBytes(bytes){return bytes>=1e9?(bytes/1e9).toFixed(2)+' GB':bytes>=1e6?(bytes/1e6).toFixed(1)+' MB':bytes>=1000?(bytes/1000).toFixed(1)+' KB':bytes+' B'}
async function storeAccountArtifact(file){
 const owner=authUser?.id;if(!owner||!authClient)throw Error(lang==='es'?'Inicia sesión para guardar archivos en tu cuenta.':'Sign in to save files to your account.');if(!(file instanceof Blob)||!file.size||file.size>(artifactCategory(file)==='videos'?150000000:10485760))throw Error(lang==='es'?'Máximo 150 MB por video y 10 MB para los demás archivos.':'Maximum 150 MB per video and 10 MB for other files.');
 const headers={'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name||'archivo'),'X-File-Size':String(file.size)};
 let response;
 if(file.size>10000000){
  const started=await (await accountStorageRequest('/files',{method:'POST',headers:{...headers,'X-Upload-Action':'start'},body:'{}'},owner)).json();
  for(let offset=0,part=1;offset<file.size;offset+=10000000,part++){const chunk=file.slice(offset,offset+10000000);await accountStorageRequest('/files',{method:'POST',headers:{...headers,'X-File-Size':String(chunk.size),'X-Upload-Action':'part','X-Upload-Id':started.id,'X-Part-Number':String(part)},body:chunk},owner)}
  response=await accountStorageRequest('/files',{method:'POST',headers:{...headers,'X-Upload-Action':'complete','X-Upload-Id':started.id},body:'{}'},owner);
 }else response=await accountStorageRequest('/files',{method:'POST',headers,body:file},owner);
 const saved=await response.json();return {...saved,path:saved.key,owner};
}
window.NunaArtifacts={store:storeAccountArtifact};
async function accountFileList(owner,category){let entries=[];for(let offset=0;;offset+=100){const {data,error}=await authClient.storage.from('nuna-files').list(owner+'/'+category,{limit:100,offset,sortBy:{column:'created_at',order:'desc'}});if(error)throw error;entries.push(...(data||[]).filter(x=>x.id));if(!data||data.length<100)break;if(offset>=9900)break}return entries}
function renderAccountStorage(panel){
 const es=lang==='es',t=(a,b)=>es?a:b,owner=authUser?.id;const status=document.createElement('p');status.setAttribute('role','status');panel.append(status);
 if(!owner||!authClient){status.textContent=t('Inicia sesión para ver tus archivos guardados.','Sign in to see your saved files.');const login=document.createElement('button');login.textContent=t('Iniciar sesión','Sign in');login.onclick=()=>{settingsDialog.close();openAuth('login')};panel.append(login);return}
 const summary=document.createElement('div');summary.className='storage-summary';const caption=document.createElement('span');caption.textContent=t('Archivos privados de tu cuenta','Private files in your account');const bytes=document.createElement('strong');bytes.textContent='…';summary.append(caption,bytes);panel.append(summary);const meter=document.createElement('progress');meter.max=15000000000;meter.value=0;meter.setAttribute('aria-label',t('Almacenamiento utilizado de 15 GB','Storage used out of 15 GB'));meter.style.width='100%';panel.append(meter);
 const upload=document.createElement('button');upload.textContent=t('Añadir archivos','Add files');upload.type='button';const input=document.createElement('input');input.type='file';input.multiple=true;input.hidden=true;upload.onclick=()=>input.click();input.onchange=async()=>{const files=[...input.files];input.value='';upload.disabled=true;let stored=0,failed=0,lastError='';for(const file of files){try{await storeAccountArtifact(file);stored++}catch(error){failed++;lastError=error.message}}status.textContent=t(`${stored} archivos guardados${failed?`; ${failed} no se pudieron guardar (máximo 150 MB por video y 10 MB para otros archivos)`:''}.`,`${stored} files saved${failed?`; ${failed} could not be saved (150 MB per video; 10 MB for other files)`:''}.`);if(lastError)status.textContent+=' '+lastError;upload.disabled=false;await refresh()};panel.append(upload,input);
 const grid=document.createElement('div');grid.className='storage-grid';panel.append(grid);const details=document.createElement('div');details.className='storage-detail';details.hidden=true;panel.append(details);
 const allowance=document.createElement('p');allowance.className='settings-note';allowance.textContent=t('15 GB por cuenta para tus archivos. Es tu espacio total, no 15 GB nuevos cada mes. Máximo 150 MB por video y 10 MB para otros archivos.','15 GB per account for your files. This is your total space, not another 15 GB every month. Maximum 150 MB per video and 10 MB for other files.');panel.append(allowance);
 const note=document.createElement('p');note.className='settings-note';note.textContent=t('Los archivos se clasifican automáticamente. Chats y proyectos conservan sus categorías. Las fotos locales antiguas de Work no se trasladan automáticamente. Guardar un archivo no lo envía a la IA.','Files are categorized automatically. Chats and projects keep their categories. Older local Work photos are not automatically moved. Saving a file does not send it to the AI.');panel.append(note);
 let categories={};const labels={photos:t('Fotos','Photos'),videos:t('Videos','Videos'),documents:t('Documentos','Documents'),audio:t('Audio','Audio'),other:t('Otros archivos','Other files'),chats:t('Chats','Chats'),projects:t('Proyectos','Projects')};
 async function refresh(){try{const [data,remote]=await Promise.all([Promise.all(artifactCategories.map(async c=>[c,await accountFileList(owner,c)])),accountStorageRequest('/files',{},owner).then(r=>r.json())]);if(authUser?.id!==owner||!panel.isConnected)return;categories=Object.fromEntries(data);for(const file of remote.files){categories[file.category]?.push({...file,provider:'r2',metadata:{size:file.size}})}let total=0;grid.replaceChildren();for(const c of [...artifactCategories,'chats','projects']){const entries=c==='chats'?custom:c==='projects'?projects:categories[c];const size=c==='chats'||c==='projects'?new Blob([JSON.stringify(entries)]).size:entries.reduce((s,f)=>s+Number(f.metadata?.size||0),0);if(artifactCategories.includes(c))total+=size;const card=document.createElement('button');card.type='button';card.className='storage-category';const title=document.createElement('strong');title.textContent=labels[c];const count=document.createElement('span');count.textContent=entries.length+' '+t('elementos','items')+' · '+fileBytes(size);card.append(title,count);card.onclick=()=>showCategory(c);grid.append(card)}bytes.textContent=fileBytes(remote.usedBytes)+(remote.limitBytes===null?t(' / Sin cuota total (administrador)',' / No total quota (administrator)'):' / 15 GB');meter.hidden=remote.limitBytes===null;allowance.textContent=remote.limitBytes===null?t('Administrador: sin cuota total de almacenamiento. Máximo 150 MB por video y 10 MB para otros archivos.','Administrator: no total storage quota. Maximum 150 MB per video and 10 MB for other files.'):allowance.textContent;meter.value=remote.usedBytes;meter.setAttribute('aria-valuetext',bytes.textContent)}catch{status.textContent=t('No se pudieron cargar tus archivos. Vuelve a abrir Almacenamiento para reintentar.','Could not load your files. Reopen Storage to try again.');bytes.textContent='—'}}
 function showCategory(category){details.hidden=false;details.replaceChildren();const h=document.createElement('h4');h.textContent=labels[category];details.append(h);const files=category==='chats'?custom:category==='projects'?projects:categories[category];if(!files.length){const p=document.createElement('p');p.textContent=t('Todavía no hay elementos en esta categoría.','No items in this category yet.');details.append(p)}
 for(const file of files){const row=document.createElement('div');row.className='storage-item';const name=document.createElement('span');name.textContent=category==='chats'?(typeof file.title==='string'?file.title:file.title?.[lang]||t('Chat','Chat')):category==='projects'?file.name:(file.provider==='r2'?file.name:file.name.replace(/^[a-f0-9-]{36}--/,''));row.append(name);
 if(artifactCategories.includes(category)){const open=document.createElement('button');open.type='button';open.textContent=t('Descargar','Download');open.onclick=async()=>{open.disabled=true;try{if(authUser?.id!==owner)throw Error();let data;if(file.provider==='r2'){data=await (await accountStorageRequest('/files/'+file.id,{},owner)).blob()}else{const result=await authClient.storage.from('nuna-files').download(owner+'/'+category+'/'+file.name);if(result.error)throw result.error;data=result.data}const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name.textContent;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{status.textContent=t('No se pudo descargar el archivo.','Could not download the file.')}finally{open.disabled=false}};row.append(open)}else if(category==='chats'){const open=document.createElement('button');open.textContent=t('Abrir chat','Open chat');open.onclick=()=>{active=file.id;settingsDialog.close();render();scrollBottom()};row.append(open)}details.append(row)}details.scrollIntoView({block:'nearest'})}
 refresh();
}
const artifactStyle=document.createElement('style');artifactStyle.textContent='.storage-item{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.storage-item>span{flex:1;min-width:130px;overflow-wrap:anywhere}.storage-item button{flex-shrink:0}';document.head.append(artifactStyle);
