// Private image-to-video jobs; only explicit requests start billable generation.
(function(){
 let source=null,waiting=false;const running=new Set();const priorSend=send,priorFiles=renderChatAttachments;
 function select(file){source=file;document.getElementById('prompt').focus();openAIStatus.textContent=lang==='es'?'Describe cómo quieres animar esta imagen. Video en 720p.':'Describe how to animate this image. Video at 720p.'}
 renderChatAttachments=function(container,files){priorFiles(container,files);const owner=authUser?.id;for(const file of files){if(file.provider!=='r2')continue;if(/^image\/(jpeg|png|webp)$/.test(file.type)){const b=document.createElement('button');b.type='button';b.textContent='▶';b.setAttribute('aria-label',lang==='es'?'Animar imagen':'Animate image');b.onclick=()=>select(file);container.append(b)}if(file.type==='video/mp4'){const video=document.createElement('video');video.controls=true;video.playsInline=true;video.preload='metadata';video.style.cssText='display:block;width:100%;max-width:640px;border-radius:14px;margin-top:12px';container.append(video);accountStorageRequest('/files/'+encodeURIComponent(file.id),{},owner).then(r=>r.blob()).then(blob=>{if(owner!==authUser?.id||!video.isConnected)return;const url=URL.createObjectURL(blob);video.src=url;const download=document.createElement('button');download.type='button';download.style.cssText='display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;margin-top:10px;border:1px solid var(--border);border-radius:12px;background:transparent;color:var(--muted)';const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');icon.style.cssText='width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round';const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M12 3v12m-5-5 5 5 5-5M5 16v4h14v-4');icon.append(path);download.append(icon);download.setAttribute('aria-label',lang==='es'?'Descargar video':'Download video');download.title=lang==='es'?'Descargar video':'Download video';download.onclick=async()=>{if(owner!==authUser?.id)return;const f=new File([blob],file.name,{type:'video/mp4'});if(navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f]})}catch{}}else{const a=document.createElement('a');a.href=url;a.download=file.name;a.target='_blank';a.rel='noopener noreferrer';a.click()}};container.append(download);const extension=document.createElement('button');extension.type='button';extension.textContent='Extender';extension.style.cssText='margin:10px;padding:10px;border-radius:12px;min-height:44px;border:1px solid var(--border);background:transparent;color:var(--text)';extension.onclick=()=>extend(file,container);container.append(extension);const observer=new MutationObserver(()=>{if(!video.isConnected){URL.revokeObjectURL(url);observer.disconnect()}});observer.observe(document.getElementById('messages'),{childList:true,subtree:true})}).catch(()=>{video.remove()})}}};
 async function extend(file,container){
  if(container.querySelector('[data-extension]'))return;
  const form=document.createElement('form');form.dataset.extension='true';form.style.cssText='display:flex;flex-wrap:wrap;gap:10px;margin:12px 0';
  const duration=document.createElement('select');duration.setAttribute('aria-label','Segundos adicionales');
  for(const seconds of [5,10,15]){const option=document.createElement('option');option.value=seconds;option.textContent='+'+seconds+' s · $'+(seconds*.1).toFixed(2);duration.append(option)}
  const prompt=document.createElement('input');prompt.placeholder='Describe cómo continúa el video';prompt.required=true;prompt.maxLength=4000;prompt.style.cssText='min-width:0;flex:1;font-size:16px';prompt.setAttribute('aria-label','Continuación del video');
  const button=document.createElement('button');button.textContent='Extender';button.type='submit';
  const cancel=document.createElement('button');cancel.type='button';cancel.textContent='Cerrar';cancel.onclick=()=>form.remove();
  const note=document.createElement('small');note.style.flexBasis='100%';note.textContent='Añade segundos al final. Costo estimado de generación; conserva el original. Máximo 30 MB para extender.';
  form.append(duration,prompt,button,cancel,note);container.append(form);prompt.focus();
  form.onsubmit=async(event)=>{event.preventDefault();const owner=authUser?.id,chat=custom.find(c=>c.id===active);if(!owner||!chat||openAIBusy)return;if(chat.videoJob){openAIStatus.textContent='Ya hay un video pendiente en este chat.';return}button.disabled=true;openAIBusy=true;
   try{const r=await fetch('/api/videos',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await authAccessToken()},body:JSON.stringify({action:'extend',videoId:file.id,duration:Number(duration.value),prompt:prompt.value})});const data=await r.json();if(!r.ok)throw Error(data.error==='source_too_large'?'El video supera 30 MB para extensión.':'No se pudo iniciar la extensión.');if(owner!==authUser?.id||!custom.includes(chat))return;chat.messages.push(['user','Extiende el video '+duration.value+' segundos: '+prompt.value]);chat.videoJob=data.job;try{localStorage.setItem('nuna-video-'+owner+'-'+chat.id,data.job)}catch{}save();render();openAIStatus.textContent='Extendiendo tu video…';resume(chat,owner)}catch(e){if(owner===authUser?.id)openAIStatus.textContent=e.message}finally{openAIBusy=false;button.disabled=false}
  };
 }
 async function resume(chat,owner){
  if(running.has(chat.id)||!chat.videoJob)return;running.add(chat.id);const job=chat.videoJob;
  try{for(let i=0;i<240;i++){
   if(authUser?.id!==owner||!custom.includes(chat))return;
   const headers={Authorization:'Bearer '+await authAccessToken()};const r=await fetch('/api/videos?job='+encodeURIComponent(job),{headers});const data=await r.json();if(!r.ok)throw Error('No se pudo completar el video.');
   if(data.status==='COMPLETED'){
    const output=await fetch('/api/videos?job='+encodeURIComponent(job)+'&download=1',{headers});if(!output.ok)throw Error('No se pudo descargar el video.');const blob=await output.blob();if(authUser?.id!==owner||!custom.includes(chat))return;
    const file=new File([blob],'NUNA-video.mp4',{type:'video/mp4'});const saved=await NunaArtifacts.store(file);if(authUser?.id!==owner||!custom.includes(chat))return;
    const index=chat.messages.length;chat.messages.push(['assistant',lang==='es'?'Aquí tienes tu video.':'Here is your video.']);chat.attachments=chat.attachments||{};chat.attachments[index]=[{...saved,name:file.name,type:file.type,size:file.size}];delete chat.videoJob;try{localStorage.removeItem('nuna-video-'+owner+'-'+chat.id)}catch{}save();render();openAIStatus.textContent=lang==='es'?'Video guardado en Videos.':'Video saved in Videos.';scrollBottom();return;
   }
   if(!['IN_QUEUE','IN_PROGRESS'].includes(data.status))throw Error('No se pudo completar el video.');
   await new Promise(resolve=>setTimeout(resolve,5000));
  }throw Error('El video sigue pendiente. Recarga para comprobarlo sin generar otro.');
  }catch(e){if(authUser?.id===owner)openAIStatus.textContent=e.message+' Recarga para volver a comprobar.'}finally{running.delete(chat.id)}
 }
 send=async function(value){const text=String(value||'').trim();const explicit=/(?:crea|genera|haz|anima|create|generate|animate).{0,40}(?:video|imagen|foto|image|photo)/i.test(text)&&/(video|anima|animate)/i.test(text)&&! /\bno\s+(?:crees|generes|hagas|quiero)/i.test(text);if(!source&&!waiting&&!explicit)return priorSend(value);if(!text||openAIBusy)return;
 const owner=authUser?.id;if(!owner||!await waitForAccount())return;let chat=custom.find(c=>c.id===active);if(chat?.videoJob){openAIStatus.textContent='Ya hay un video pendiente en este chat.';resume(chat,owner);return}
 const photo=source||pendingAttachments.find(f=>f.provider==='r2'&&/^image\/(jpeg|png|webp)$/.test(f.type))||Object.values(chat?.attachments||{}).flat().reverse().find(f=>f.provider==='r2'&&/^image\/(jpeg|png|webp)$/.test(f.type));if(!photo){openAIStatus.textContent=lang==='es'?'Adjunta una foto o crea una imagen primero para animarla.':'Attach a photo or create an image first to animate it.';return}
 if(!chat){chat={id:crypto.randomUUID(),title:text.slice(0,45),messages:[],project:currentProject};custom.unshift(chat);active=chat.id;assignNewChatSection(chat)}
 openAIBusy=true;openAIStatus.textContent='Preparando tu video en 720p…';
 try{const r=await fetch('/api/videos',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await authAccessToken()},body:JSON.stringify({prompt:text,imageId:photo.id})});const data=await r.json();if(!r.ok)throw Error(data.error==='daily_limit'?'Alcanzaste el límite diario.':'No se pudo iniciar el video.');if(authUser?.id!==owner||!custom.includes(chat))return;
 chat.messages.push(['user',text]);chat.videoJob=data.job;try{localStorage.setItem('nuna-video-'+owner+'-'+chat.id,data.job)}catch{}source=null;waiting=false;pendingAttachments=[];document.getElementById('prompt').value='';save();render();refreshAttachments();openAIStatus.textContent='Creando tu video… puedes seguir usando el chat.';resume(chat,owner);
 }catch(e){if(authUser?.id===owner)openAIStatus.textContent=e.message}finally{openAIBusy=false}
 };
 const priorNew=newChat;newChat=function(){source=null;waiting=false;priorNew()};['new-chat','new-top'].forEach(id=>document.getElementById(id).onclick=newChat);
 window.NunaVideos={begin(){waiting=true;source=null;attachmentMenu.hidden=true;attachmentButton.setAttribute('aria-expanded','false');attachmentInput.removeAttribute('capture');attachmentInput.multiple=false;attachmentInput.accept='image/jpeg,image/png,image/webp';attachmentInput.click();openAIStatus.textContent=lang==='es'?'Adjunta una imagen o usa la última foto del chat y describe cómo quieres animarla.':'Attach an image or use the last chat photo and describe the animation.';document.getElementById('prompt').focus()}};
 const priorRender=render;render=function(){priorRender();const owner=authUser?.id;if(owner)for(const chat of custom){try{chat.videoJob=chat.videoJob||localStorage.getItem('nuna-video-'+owner+'-'+chat.id)}catch{}if(chat.videoJob)resume(chat,owner)}};render();
})();
