const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../composer-models.js'),'utf8');
function setup(values={}){const elements=[],events={},store=new Map(Object.entries(values)),calls=[];class Element{constructor(){this.children=[];this.value='';}append(...els){this.children.push(...els)}after(){}setAttribute(){}replaceChildren(){this.children=[]}get options(){return this.children.flatMap(g=>g.children||[])}get selectedOptions(){return this.options.filter(o=>o.value===this.value)}}
const context={document:{createElement(){const e=new Element();elements.push(e);return e},getElementById(){return new Element()}},Option:function(text,value){this.text=text;this.value=value},window:{addEventListener(n,fn){events[n]=fn}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},authUser:null,lang:'es',preferredModel:'grok',providerModels:[{id:'grok',name:'Grok'}],openAIBusy:false,NunaImages:{cancel(){calls.push('image-cancel')},begin(){calls.push('image-begin')}},NunaVideos:{cancel(){},configure(v){calls.push(v)},begin(){}},NunaMedia:{},render(){},custom:[],saveModels(){},updateModelLabel(){},save(){},openAIStatus:{}};vm.runInNewContext(code,context);return{context,store,calls,events,select:elements.find(e=>e.id==='composer-model')}}
test('account event restores Veo immediately without waiting for chat loading',()=>{const s=setup({'nuna-composer-owner':JSON.stringify({model:'video:gemini',duration:10})});s.context.authUser={id:'owner'};s.events['nuna-account-changed']();assert.equal(s.select.value,'video:gemini');assert.equal(s.calls.at(-1).engine,'gemini');s.context.render();assert.equal(s.select.value,'video:gemini');});
test('last selection survives initial page loading while separate accounts restore their own values',()=>{const s=setup({'nuna-composer-last':JSON.stringify({model:'video:gemini',duration:10}),'nuna-composer-other':JSON.stringify({model:'video:grok',duration:15})});assert.equal(s.select.value,'video:gemini');s.context.authUser={id:'other'};s.events['nuna-account-changed']();assert.equal(s.select.value,'video:grok');assert.equal(s.calls.at(-1).duration,15);s.select.value='video:gemini';s.select.onchange();assert.equal(JSON.parse(s.store.get('nuna-composer-other')).model,'video:gemini');assert.equal(JSON.parse(s.store.get('nuna-composer-last')).model,'video:gemini');});
test('the free plan switches a restored image choice back to chat once the plan is known',()=>{const s=setup({'nuna-composer-u1':JSON.stringify({model:'image:default'})});s.context.providerModels=[{id:'grok',name:'Grok'},{id:'qwen',name:'Qwen'}];s.context.authUser={id:'u1'};s.events['nuna-account-changed']();assert.equal(s.select.value,'image:default');assert.equal(s.calls.at(-1),'image-begin');
 s.context.window.authUsage={used:1,limit:30,admin:false,paidModels:false};s.context.render();assert.equal(s.select.value,'chat:qwen');assert.equal(s.calls.at(-1),'image-cancel');assert.equal(s.select.options.find(o=>o.value==='chat:qwen').textContent,'Qwen · Gratis');assert.equal(s.select.options.find(o=>o.value==='chat:grok').disabled,true);
 // The stored choice stays for when the account moves to a paid plan.
 assert.equal(JSON.parse(s.store.get('nuna-composer-u1')).model,'image:default');});
test('the owner access code keeps chat models open on a free account, but not images',()=>{const s=setup();s.context.providerModels=[{id:'grok',name:'Grok'},{id:'qwen',name:'Qwen'}];s.context.openAITestCode='owner-code-1234567890';s.context.authUser={id:'u1'};s.context.window.authUsage={used:1,limit:30,admin:false,paidModels:false};s.events['nuna-account-changed']();
 assert.equal(s.select.options.find(o=>o.value==='chat:grok').disabled,undefined);assert.equal(s.select.options.find(o=>o.value==='image:default').disabled,true);assert.equal(s.select.value,'chat:grok');});
