const {test}=require('node:test');const assert=require('node:assert/strict');const handler=require('../api/images');
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test';process.env.OPENAI_API_KEY='test-key';process.env.NUNA_ADMIN_EMAILS='admin@example.com';
const token='eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vcm1hbEBleGFtcGxlLmNvbSJ9.signature';
const response=()=>({setHeader(){},status(n){this.code=n;return this},json(body){this.body=body;return this}});
function mock(overrides={}){let calls=[];const fetch=async(url,options)=>{calls.push({url,options});if(url.endsWith('/auth/v1/user'))return{ok:true,json:async()=>({id:'normal-user',email_confirmed_at:'now'})};if(url.includes('consume_ai_message'))return{status:200,json:async()=>[{ok:true,reservation_id:'reservation'}]};if(url.includes('refund_ai_message'))return{status:200,json:async()=>true};if(url.includes('workers.dev'))return{ok:overrides.allowed!==false,headers:new Headers({'content-type':'image/png'}),arrayBuffer:async()=>new Uint8Array([137,80,78,71,13,10,26,10]).buffer};return{ok:overrides.success!==false,status:overrides.success===false?429:200,json:async()=>overrides.success===false?{error:{}}:{data:[{b64_json:'aW1hZ2U='}]}}};return{fetch,calls}}
test('generation validates account, reserves usage and uses a single low-cost image request',async()=>{const old=global.fetch,m=mock();global.fetch=m.fetch;try{const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'A teal fish'}},res);assert.equal(res.code,200);assert.equal(res.body.edited,false);const req=m.calls.find(c=>c.url.endsWith('/generations'));assert.equal(JSON.parse(req.options.body).n,1);assert.equal(JSON.parse(req.options.body).quality,'low');assert.ok(!JSON.stringify(res.body).includes('test-key'));assert.ok(m.calls.find(c=>c.url.includes('consume_ai_message')))}finally{global.fetch=old}});
test('edits fetch only private fixed storage with the user token and send multipart image',async()=>{const old=global.fetch,m=mock();global.fetch=m.fetch;try{const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'Make the fish orange',imageId:'private-file'}},res);assert.equal(res.code,200);assert.equal(res.body.edited,true);const storage=m.calls.find(c=>c.url.includes('workers.dev'));assert.equal(storage.options.headers.Authorization,'Bearer '+token);const edit=m.calls.find(c=>c.url.endsWith('/edits'));assert.ok(edit.options.body instanceof FormData);assert.equal(edit.options.body.get('image[]').type,'image/png')}finally{global.fetch=old}});
test('unsigned requests, arbitrary URLs and foreign private files never call image provider',async()=>{const old=global.fetch,m=mock({allowed:false});global.fetch=m.fetch;try{const none=response();await handler({method:'POST',headers:{},body:{prompt:'fish'}},none);assert.equal(none.code,401);for(const imageId of ['https://evil.example/a','foreign-file']){const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'fish',imageId}},res);assert.ok([400,403].includes(res.code))}assert.ok(!m.calls.some(c=>c.url.includes('api.openai.com')))}finally{global.fetch=old}});
test('provider rejection refunds the reserved daily request and does not return an image',async()=>{const old=global.fetch,m=mock({success:false});global.fetch=m.fetch;try{const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'fish'}},res);assert.equal(res.code,429);assert.ok(m.calls.some(c=>c.url.includes('refund_ai_message')));assert.equal(res.body.image,undefined)}finally{global.fetch=old}});

test('FLUX generation uses server key and inline JPEG, preserving private output flow',async()=>{const old=global.fetch,m=mock();process.env.FAL_KEY='fal-test-secret';global.fetch=async(url,options)=>url.startsWith('https://fal.run/')?(m.calls.push({url,options}),{ok:true,json:async()=>({images:[{url:'data:image/jpeg;base64,aW1hZ2U='}],has_nsfw_concepts:[false]})}):m.fetch(url,options);try{const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'A fish'}},res);assert.equal(res.code,200);assert.equal(res.body.image,'aW1hZ2U=');const call=m.calls.find(c=>c.url.includes('fal.run'));assert.equal(call.options.headers.Authorization,'Key fal-test-secret');assert.equal(JSON.parse(call.options.body).enable_safety_checker,true);assert.equal(JSON.parse(call.options.body).num_images,1);assert.ok(!JSON.stringify(res.body).includes('fal-test-secret'));}finally{delete process.env.FAL_KEY;global.fetch=old}});
test('fal editing sends only authorized source bytes and marks result edited',async()=>{const old=global.fetch,m=mock();process.env.FAL_KEY='fal-test-secret';global.fetch=async(url,options)=>url.startsWith('https://fal.run/')?(m.calls.push({url,options}),{ok:true,json:async()=>({images:[{url:'data:image/jpeg;base64,aW1hZ2U='}],has_nsfw_concepts:[false]})}):m.fetch(url,options);try{const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'Make it orange',imageId:'private-file'}},res);assert.equal(res.code,200);assert.equal(res.body.edited,true);const call=m.calls.find(c=>c.url.includes('fal.run'));assert.ok(call.url.endsWith('/flux-kontext/dev'));assert.equal(JSON.parse(call.options.body).image_url,'data:image/png;base64,iVBORw0KGgo=');assert.ok(!m.calls.some(c=>c.url.includes('api.openai.com')));}finally{delete process.env.FAL_KEY;global.fetch=old}});
