const {test}=require('node:test');const assert=require('node:assert/strict');
const {localQwenConfig,localQwenReply}=require('../api/_local-qwen');const {createBridge}=require('../scripts/local-qwen-bridge.cjs');
process.env.NUNA_LOCAL_QWEN_EMAIL='owner@example.com';process.env.NUNA_LOCAL_QWEN_URL='https://private.example.com';process.env.NUNA_LOCAL_QWEN_KEY='a'.repeat(64);
const owner={id:'owner',email:'owner@example.com',email_confirmed_at:'yes'};
test('only verified allowlisted account gets local route, no access-code shortcut',()=>{assert.ok(localQwenConfig(owner));assert.equal(localQwenConfig(null),null);assert.equal(localQwenConfig({...owner,email:'other@example.com'}),null);assert.equal(localQwenConfig({...owner,email_confirmed_at:null}),null)});
test('local response and unavailable/long context fallback signals',async()=>{const old=fetch;try{global.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:'Hola'},finish_reason:'stop'}]})});assert.equal((await localQwenReply(owner,'system',[{role:'user',content:'Hola'}])).text,'Hola');global.fetch=async()=>{throw Error('offline')};assert.equal((await localQwenReply(owner,'system',[{role:'user',content:'Hola'}])).reason,'unavailable');assert.equal((await localQwenReply(owner,'x'.repeat(16001),[])).reason,'context');assert.equal((await localQwenReply(null,'',[])).attempted,false)}finally{global.fetch=old}});
test('bridge rejects anonymous calls and arbitrary paths; pins model and token limit',async()=>{let forwarded;const key='b'.repeat(64);const server=createBridge({key},async(url,options)=>{forwarded=JSON.parse(options.body);return{ok:true,json:async()=>({choices:[{message:{content:'Hola'},finish_reason:'stop'}]})}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{assert.equal((await fetch(base+'/v1/chat/completions',{method:'POST'})).status,401);const headers={Authorization:'Bearer '+key,'Content-Type':'application/json'};assert.equal((await fetch(base+'/anything',{headers})).status,404);const r=await fetch(base+'/v1/chat/completions',{method:'POST',headers,body:JSON.stringify({model:'arbitrary',max_tokens:99999,messages:[{role:'user',content:'Hola'}]})});assert.equal(r.status,200);assert.equal(forwarded.model,'qwen/qwen3.5-9b');assert.equal(forwarded.max_tokens,600);assert.equal(forwarded.reasoning_effort,'none')}finally{await new Promise(r=>server.close(r))}});
test('chat uses local only for owner, cloud fallback on failure, and counts once',async()=>{
 const handler=require('../api/chat');const old=fetch;process.env.NUNA_LOCAL_QWEN_FALLBACK='true';process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test';process.env.DASHSCOPE_API_KEY='cloud-test';process.env.NUNA_ADMIN_EMAILS='';
 let user=owner,offline=false,calls=[];
 global.fetch=async(url,options)=>{calls.push(url);if(url.includes('/auth/v1/user'))return{ok:true,json:async()=>user};if(url.includes('my_plan'))return{status:200,json:async()=>[{plan:'gratis',plan_name:'Gratis',daily_messages:30,paid_models:false,storage_gb:2,daily_images:0,daily_videos:0,daily_voice:0}]};if(url.includes('consume_ai_message'))return{status:200,json:async()=>[{ok:true,used_today:1,day_limit:30,reservation_id:'one'}]};if(url.startsWith('https://private.example.com')){if(offline)throw Error('offline');return{ok:true,json:async()=>({choices:[{message:{content:'local'},finish_reason:'stop'}]})}}if(url.includes('dashscope'))return{ok:true,json:async()=>({choices:[{message:{content:'cloud'}}]})};throw Error('Unexpected request')};
 const run=async()=>{const res={setHeader(){},status(n){this.code=n;return this},json(b){this.body=b;return this}};await handler({method:'POST',headers:{authorization:'Bearer a.valid.test_token_12345678'},body:{provider:'qwen',messages:[{role:'user',content:'Hola'}]}},res);assert.equal(res.code,200);return res.body};
 try{assert.equal((await run()).execution,'local');assert.equal(calls.filter(u=>u.includes('consume_ai_message')).length,1);assert.equal(calls.some(u=>u.includes('dashscope')),false);offline=true;calls=[];assert.equal((await run()).execution,'cloud-fallback');assert.equal(calls.filter(u=>u.includes('consume_ai_message')).length,1);user={...owner,email:'other@example.com'};calls=[];assert.equal((await run()).text,'cloud');assert.equal(calls.some(u=>u.startsWith('https://private')),false)}finally{global.fetch=old}
});
