const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('generated MP4 travels through download and private account storage; a failed save keeps the same recoverable job',async()=>{
 const video=fs.readFileSync('videos.js','utf8'),storage=fs.readFileSync('storage.js','utf8');
 for(const failFirst of [false,true]){
  const chat={id:'chat',videoJob:'encrypted-job',messages:[],attachments:{}},calls=[];let uploads=0;
  const env={window:{},Headers,Response,Blob,File,Uint8Array,Set,Map,lang:'es',authUser:{id:'owner'},authClient:{auth:{getSession:async()=>({data:{session:{access_token:'token'}}})}},custom:[chat],running:new Set(),completedCallbacks:new Map(),reportedFailures:new Set(),localStorage:{removeItem(){}},authAccessToken:async()=> 'token',openAIStatus:{},save(){},render(){},scrollBottom(){},fetch:async(url,opts)=>{calls.push(url);if(url.startsWith('/api/videos?')){if(url.includes('download=1'))return new Response(Uint8Array.from([0,0,0,24,102,116,121,112,109,112,52,50]),{headers:{'Content-Type':'video/mp4'}});return Response.json({status:'COMPLETED'})}if(url.endsWith('workers.dev/files')){uploads++;assert.equal(opts.headers.get('Authorization'),'Bearer token');assert.equal(opts.body.type,'video/mp4');assert.equal(opts.headers.get('X-File-Name'),'NUNA-video.mp4');if(failFirst&&uploads===1)return Response.json({error:'private_error'},{status:503});return Response.json({id:'file',provider:'r2',key:'private/key'})}throw Error('unexpected URL')}};
  vm.createContext(env);vm.runInContext(storage.slice(0,storage.indexOf('async function accountFileList')),env);env.NunaArtifacts=env.window.NunaArtifacts;vm.runInContext(video.slice(video.indexOf(' async function resume'),video.indexOf(' send=async function'))+';this.resumeJob=resume;',env);
  await env.resumeJob(chat,'owner');if(failFirst){assert.equal(chat.videoJob,'encrypted-job');assert.match(chat.messages[0][1],/se generó.*no se pudo guardar/);assert.ok(!JSON.stringify(chat).includes('private_error'));await env.resumeJob(chat,'owner')}
  assert.equal(chat.videoJob,undefined);assert.equal(chat.messages.at(-1)[1],'Aquí tienes tu video.');assert.equal(chat.attachments[chat.messages.length-1][0].id,'file');assert.equal(uploads,failFirst?2:1);assert.ok(calls.every(url=>url!=='/api/videos'));assert.equal(env.running.size,0);
 }
});
