const {test}=require('node:test'),assert=require('node:assert/strict'),handler=require('../api/videos');
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test';process.env.FAL_KEY='test-video-key';
const token='eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vcm1hbEBleGFtcGxlLmNvbSJ9.signature';
const res=()=>({setHeader(){},status(n){this.code=n;return this},json(b){this.body=b;return this}});
test('video jobs require private source, reserve one request and reject another account or tampered job',async()=>{const old=global.fetch;let owner='one',provider=0;global.fetch=async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return{ok:true,json:async()=>({id:owner,email_confirmed_at:'now'})};if(url.includes('my_plan'))return{status:200,json:async()=>[{plan:'plus',plan_name:'Plus',daily_messages:150,paid_models:true,storage_gb:null,daily_images:10,daily_videos:1,daily_voice:2}]};if(url.includes('consume_ai_media'))return{status:200,json:async()=>[{ok:true,reservation_id:'r'}]};if(url.includes('workers.dev'))return{ok:true,arrayBuffer:async()=>new Uint8Array([137,80,78,71,13,10,26,10]).buffer};if(url.endsWith('/turbo')){provider++;const b=JSON.parse(opts.body);assert.equal(b.resolution,'720p');assert.equal(b.enable_output_safety_checker,true);return{ok:true,json:async()=>({request_id:'job-one'})}}if(url.endsWith('/status'))return{ok:true,json:async()=>({status:'IN_PROGRESS'})};throw Error('unexpected')};try{let r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'Animate',imageId:'https://evil.example'}},r);assert.equal(r.code,400);r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'Animate',imageId:'photo'}},r);assert.equal(r.code,202);assert.equal(provider,1);const job=r.body.job;assert.ok(!job.includes('test-video-key'));r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job}},r);assert.equal(r.body.status,'IN_PROGRESS');owner='two';r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job}},r);assert.equal(r.code,403);r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job:job.slice(0,-2)+'xx'}},r);assert.equal(r.code,400)}finally{global.fetch=old}});
test('extension validates duration, private MP4 and account ownership',async()=>{const old=global.fetch;let owner='one',calls=0;try{global.fetch=async(url,opts)=>{if(url.includes('workers.dev'))return{ok:true,arrayBuffer:async()=>Uint8Array.from([0,0,0,24,102,116,121,112,109,112,52,50]).buffer};return fetchMock(url,opts)};const fetchMock=async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return{ok:true,json:async()=>({id:owner,email_confirmed_at:'now'})};if(url.includes('my_plan'))return{status:200,json:async()=>[{plan:'plus',plan_name:'Plus',daily_messages:150,paid_models:true,storage_gb:null,daily_images:10,daily_videos:1,daily_voice:2}]};if(url.includes('consume_ai_media'))return{status:200,json:async()=>[{ok:true,reservation_id:'r'}]};if(url.endsWith('/extend-video')){calls++;const b=JSON.parse(opts.body);assert.equal(b.duration,5);assert.equal(b.mode,'end');assert.match(b.video_url,/^data:video\/mp4;base64,/);return{ok:true,json:async()=>({request_id:'extension-one'})}}if(url.endsWith('/status'))return{ok:true,json:async()=>({status:'IN_PROGRESS'})};throw Error('unexpected')};let r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{action:'extend',videoId:'video',duration:100,prompt:'Continue swimming'}},r);assert.equal(r.code,400);assert.equal(calls,0);r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{action:'extend',videoId:'video',duration:5,prompt:'Continue swimming'}},r);assert.equal(r.code,202);const job=r.body.job;r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job}},r);assert.equal(r.body.status,'IN_PROGRESS');owner='two';r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job}},r);assert.equal(r.code,403)}finally{global.fetch=old}});
test('configured default creates direct videos, including legacy image requests, and protects completed downloads',async()=>{
 const old=global.fetch,oldEngine=process.env.NUNA_VIDEO_ENGINE,oldKey=process.env.XAI_API_KEY;process.env.NUNA_VIDEO_ENGINE='grok';process.env.XAI_API_KEY='direct-key';let owner='one',image=false,starts=0,polls=0;
 global.fetch=async(url,opts)=>{
  if(url.endsWith('/auth/v1/user'))return{ok:true,json:async()=>({id:owner,email_confirmed_at:'now'})};
  if(url.includes('my_plan'))return{status:200,json:async()=>[{plan:'plus',paid_models:true,daily_messages:150,daily_videos:1}]};
  if(url.includes('consume_ai_media'))return{status:200,json:async()=>[{ok:true,reservation_id:'r'}]};
  if(url.includes('workers.dev'))return{ok:true,arrayBuffer:async()=>new Uint8Array([137,80,78,71,13,10,26,10]).buffer};
  if(url.endsWith('/videos/generations')){starts++;const b=JSON.parse(opts.body);assert.equal(b.duration,5);assert.equal(Boolean(b.image),image);assert.equal(opts.headers.Authorization,'Bearer direct-key');return{ok:true,json:async()=>({request_id:'direct-job'})}}
  if(url.endsWith('/videos/direct-job')){polls++;return{ok:true,json:async()=>({status:'done',video:{url:'https://vidgen.x.ai/video.mp4'}})}}
  if(url==='https://vidgen.x.ai/video.mp4')return{ok:true,headers:new Headers(),body:(async function*(){yield Buffer.from([0,0,0,24,102,116,121,112])})()};
  throw Error('unexpected '+url);
 };
 try{
  for(const body of [{prompt:'Create a swimming fish video'},{prompt:'Animate',engine:'wan',imageId:'photo'}]){image=!!body.imageId;let r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body},r);assert.equal(r.code,202);const job=r.body.job;r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job}},r);assert.equal(r.body.status,'COMPLETED');owner='other';r=res();await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job,download:'1'}},r);assert.equal(r.code,403);owner='one';r=res();const chunks=[];r.write=b=>chunks.push(b);r.end=()=>{r.ended=true};await handler({method:'GET',headers:{authorization:'Bearer '+token},query:{job,download:'1'}},r);assert.equal(r.ended,true);assert.equal(Buffer.concat(chunks).toString('ascii',4,8),'ftyp')}
  assert.equal(starts,2);assert.equal(polls,4);
 }finally{global.fetch=old;if(oldEngine===undefined)delete process.env.NUNA_VIDEO_ENGINE;else process.env.NUNA_VIDEO_ENGINE=oldEngine;if(oldKey===undefined)delete process.env.XAI_API_KEY;else process.env.XAI_API_KEY=oldKey}
});
test('direct video rejects provider errors safely and never permits an untrusted output host',async()=>{
 const direct=require('../api/_direct-video'),old=global.fetch,oldKey=process.env.XAI_API_KEY;process.env.XAI_API_KEY='key';
 try{for(const [status,error,message] of [[401,'provider_auth','invalid key SECRET'],[402,'provider_credit','insufficient credit'],[404,'provider_model_missing','model not found'],[429,'provider_limit','rate limit']]){global.fetch=async()=>({ok:false,status,json:async()=>({error:message})});await assert.rejects(direct.start('grok','fish',5),new RegExp('^Error: '+error+'$'))}
 global.fetch=async()=>({ok:true,json:async()=>({status:'done',video:{url:'https://attacker.example/video.mp4'}})});await assert.rejects(direct.poll({engine:'grok',id:'job'}),/invalid_answer/);
 }finally{global.fetch=old;if(oldKey===undefined)delete process.env.XAI_API_KEY;else process.env.XAI_API_KEY=oldKey}
});
test('known provider rejection refunds quota, but ambiguous network failure keeps the reservation and hides details',async()=>{
 const old=global.fetch,oldEngine=process.env.NUNA_VIDEO_ENGINE,oldKey=process.env.XAI_API_KEY;process.env.NUNA_VIDEO_ENGINE='grok';process.env.XAI_API_KEY='key';let mode='reject',refunds=0,spent=0;
 global.fetch=async(url)=>{if(url.endsWith('/auth/v1/user'))return{ok:true,json:async()=>({id:'one',email_confirmed_at:'now'})};if(url.includes('my_plan'))return{status:200,json:async()=>[{plan:'plus',paid_models:true,daily_messages:150,daily_videos:1}]};if(url.includes('consume_ai_media')){spent++;return{status:200,json:async()=>[{ok:true,reservation_id:'r'}]}}if(url.includes('refund_ai_message')){refunds++;return{status:200,json:async()=>true}}if(url.endsWith('/videos/generations')){if(mode==='network')throw Error('private upstream details');return{ok:false,status:402,json:async()=>({error:'insufficient credit PRIVATE'})}}throw Error('unexpected')};
 try{let r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'Create a fish video'}},r);assert.equal(r.body.error,'provider_credit');assert.equal(refunds,1);mode='network';r=res();await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{prompt:'Create a fish video'}},r);assert.equal(r.body.error,'video_unavailable');assert.equal(refunds,1);assert.equal(spent,2);assert.ok(!JSON.stringify(r.body).includes('private'))}finally{global.fetch=old;if(oldEngine===undefined)delete process.env.NUNA_VIDEO_ENGINE;else process.env.NUNA_VIDEO_ENGINE=oldEngine;if(oldKey===undefined)delete process.env.XAI_API_KEY;else process.env.XAI_API_KEY=oldKey}
});
