const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('voice queues one video, reports pending truthfully and attaches completion only to the owning session',async()=>{
 const s=fs.readFileSync('voice.js','utf8');const sent=[],records=[];let attempts=0,complete;
 const env={Set,voiceGeneration:1,voiceConnection:{send:e=>sent.push(e)},voiceOwner:'owner',voiceChat:{},authUser:{id:'owner'},voiceRecords:records,voiceSetStatus(){},vText:a=>a,storeVoiceRecords(){},window:{NunaVideos:{create:async(prompt,owner,chat,callback)=>{attempts++;complete=callback;return{queued:true}},errorMessage:c=>'Safe '+c}}};vm.createContext(env);vm.runInContext('const voiceClockCalls=new Set();'+s.slice(s.indexOf('async function answerVoiceVideo'),s.indexOf('async function answerVoiceClock'))+';this.answer=answerVoiceVideo;',env);
 const call={name:'create_video',call_id:'one',arguments:JSON.stringify({prompt:'A swimming fish video'})};await env.answer(call);await env.answer(call);assert.equal(attempts,1);assert.equal(records.length,0);const output=JSON.parse(sent[0].item.output);assert.equal(output.queued,true);assert.match(output.instructions,/Do not claim it is already finished/);assert.equal(complete({id:'file'}),true);assert.equal(records[0].files[0].id,'file');env.voiceGeneration++;assert.equal(complete({id:'late'}),false);assert.equal(records.length,1);
 env.window.NunaVideos.create=async()=>{throw Error('secret-provider-details')};await env.answer({...call,call_id:'two'});const failure=JSON.parse(sent[2].item.output);assert.equal(failure.error,'video_failed');assert.ok(!JSON.stringify(sent).includes('secret-provider-details'));
});
test('voice video queue keeps recoverable job, avoids duplicate submission and requires an image for animation',async()=>{
 const s=fs.readFileSync('videos.js','utf8'),chat={id:'chat',attachments:{}},requests=[],resumed=[];let pending;
 const env={window:{},authUser:{id:'owner'},custom:[chat],completedCallbacks:new Map(),submittingChats:new Set(),authAccessToken:async()=> 'token',localStorage:{setItem(k,v){assert.match(k,/owner/);assert.equal(v,'encrypted-job')}},save(){},resume:(...a)=>resumed.push(a),fetch:async(u,o)=>{requests.push(JSON.parse(o.body));return new Promise(r=>pending=r)}};vm.createContext(env);vm.runInContext(s.slice(s.indexOf(' async function queueVoiceVideo'),s.indexOf(' const priorNew=newChat;'))+';this.create=queueVoiceVideo;',env);
 const task=env.create('Create a fish video','owner',chat);await new Promise(r=>setImmediate(r));await assert.rejects(env.create('Create another video','owner',chat),/video_pending/);pending({ok:true,json:async()=>({job:'encrypted-job'})});await task;assert.equal(requests.length,1);assert.equal(requests[0].engine,'default');assert.equal(requests[0].imageId,undefined);assert.equal(chat.videoJob,'encrypted-job');assert.equal(resumed.length,1);delete chat.videoJob;await assert.rejects(env.create('Anima esta imagen','owner',chat),/image_required/);assert.equal(chat.videoJob,undefined);assert.equal(requests.length,1);await assert.rejects(env.create('Create a video','other',chat),/session_expired/);
});
