const {test}=require('node:test'),assert=require('node:assert/strict');const handler=require('../api/voice');
Object.assign(process.env,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',NUNA_VOICE_GATEWAY_URL:'https://voice.example.com',NUNA_VOICE_GATEWAY_SECRET:'s'.repeat(40),NUNA_ADMIN_EMAILS:''});
const token='account.confirmed.token_of_sufficient_length',response=()=>({setHeader(){},status(n){this.code=n;return this},json(b){this.body=b;return this}});
function mock({confirmed=true,paid=true,limit=false,gateway=true}={}){const calls=[];return {calls,fetch:async(url,o={})=>{const b=o.body?JSON.parse(o.body):null;calls.push({url,b});if(url.endsWith('/auth/v1/user'))return{ok:true,json:async()=>({id:'a'.repeat(8)+'-aaaa-aaaa-aaaa-'+'a'.repeat(12),email:'person@example.com',email_confirmed_at:confirmed?'now':null})};if(url.includes('my_plan_limits'))return{status:200,json:async()=>[{plan:paid?'plus':'gratis',daily_messages:paid?150:30,paid_models:paid,daily_voice:paid?2:0}]};if(url.includes('consume_ai_media'))return{status:200,json:async()=>[{ok:!limit,reservation_id:limit?null:'r1',kind_limit_reached:limit}]};if(url.includes('refund_ai_message'))return{status:200,json:async()=>true};if(url.startsWith('https://voice.example.com/health?'))return{ok:gateway,json:async()=>({ready:gateway})};if(url==='https://voice.example.com/sessions')return{ok:gateway,json:async()=>({url:'wss://voice.example.com/voice/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',protocol:'nuna-ticket.'+'a'.repeat(43)})};throw Error('Unexpected upstream '+url)}}}
async function run(req,fixture){const old=fetch;global.fetch=fixture.fetch;try{const res=response();await handler(req,res);return res}finally{global.fetch=old}}
const request=(method='POST',body={transport:'websocket'})=>({method,headers:{authorization:'Bearer '+token},body});
test('confirmed paid account gets only a one-use gateway ticket, never OpenAI credentials',async()=>{const f=mock();const res=await run(request(),f);assert.equal(res.code,200);assert.ok(res.body.url.startsWith('wss://voice.example.com'));assert.equal(res.body.clientDurationSeconds,300);assert.equal(res.body.model,undefined);assert.equal(res.body.token,undefined);assert.equal(f.calls.some(c=>c.url.includes('openai.com')),false);const session=f.calls.find(c=>c.url.endsWith('/sessions')).b.session;assert.equal(session.audio.output.voice,'marin');assert.equal(session.audio.input.format.rate,24000);assert.equal(f.calls.find(c=>c.url.includes('consume_ai_media')).b.p_kind_limit,2)});
test('anonymous, unconfirmed, free and exhausted accounts cannot obtain a voice ticket',async()=>{let f=mock();let res=await run({method:'POST',headers:{}},f);assert.equal(res.code,401);for(const [opts,status]of [[{confirmed:false},401],[{paid:false},403],[{limit:true},429]]){f=mock(opts);res=await run(request(),f);assert.equal(res.code,status);assert.equal(f.calls.some(c=>c.url.endsWith('/sessions')),false)}});
test('no gateway means voice fails closed before quota consumption or provider calls',async()=>{const saved=process.env.NUNA_VOICE_GATEWAY_SECRET;delete process.env.NUNA_VOICE_GATEWAY_SECRET;try{const f=mock();const res=await run(request(),f);assert.equal(res.code,503);assert.equal(res.body.error,'voice_gateway_unavailable');assert.equal(f.calls.some(c=>c.url.includes('consume_ai_media')||c.url.includes('openai.com')),false)}finally{process.env.NUNA_VOICE_GATEWAY_SECRET=saved}});
test('checking availability does not consume quota and direct WebRTC bypass is refused',async()=>{let f=mock();let res=await run(request('GET'),f);assert.equal(res.code,200);assert.equal(f.calls.some(c=>c.url.includes('consume_ai_media')),false);f=mock();res=await run(request('POST',{sdp:'v=0\nm=audio'}),f);assert.equal(res.code,400);assert.equal(f.calls.some(c=>c.url.includes('consume_ai_media')),false)});
test('gateway failure returns reserved quota and never yields direct provider credentials',async()=>{const f=mock({gateway:false}),res=await run(request(),f);assert.equal(res.code,502);assert.ok(f.calls.some(c=>c.url.includes('refund_ai_message')));assert.equal(res.body.token,undefined)});

test('availability never reports ready when the provider health check fails',async()=>{const f=mock({gateway:false}),res=await run(request('GET'),f);assert.equal(res.code,503);assert.equal(f.calls.some(c=>c.url.includes('consume_ai_media')),false)});
