const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
test('natural draw requests route to images while explicit negation stays text',()=>{const env={detect:require('../image-intent').imageRequest};for(const text of ['Dibuja una ballena','Dibújame una ballena','Por favor, dibuja una ballena'])assert.equal(env.detect(text),true);assert.equal(env.detect('No quiero que dibujes una ballena'),false)});
test('voice communicates a specific image failure without retrying or leaking upstream details',async()=>{
 const s=fs.readFileSync('voice.js','utf8');
 for(const code of ['provider_credit','provider_auth','image_storage_failed','unexpected-private-detail']){
  const sent=[],statuses=[];let attempts=0;
  const env={Set,voiceGeneration:1,voiceConnection:{send:e=>sent.push(e)},voiceOwner:'owner',voiceChat:{},authUser:{id:'owner'},voiceRecords:[],voiceSetStatus:m=>statuses.push(m),vText:a=>a,storeVoiceRecords(){},window:{NunaImages:{create:async()=>{attempts++;throw Error(code)},errorMessage:c=>'Safe message: '+c}}};
  vm.createContext(env);vm.runInContext('const voiceClockCalls=new Set();'+s.slice(s.indexOf('async function answerVoiceImage'),s.indexOf('async function answerVoiceClock'))+';this.answer=answerVoiceImage;',env);
  const call={name:'create_image',call_id:'one',arguments:'{"prompt":"A fish"}'};await env.answer(call);await env.answer(call);
  assert.equal(attempts,1);assert.equal(env.voiceRecords.length,0);const output=JSON.parse(sent[0].item.output);
  assert.equal(output.ok,false);assert.equal(output.error,code==='unexpected-private-detail'?'image_failed':code);assert.match(output.instructions,/Do not claim success/);assert.ok(statuses.includes(output.user_message));assert.ok(!JSON.stringify(sent).includes('unexpected-private-detail'));
 }
});
test('voice image creation distinguishes provider failure from failure to save generated bytes',async()=>{
 const s=fs.readFileSync('images.js','utf8');const source=s.slice(s.indexOf(' function imageErrorMessage'),s.indexOf('\n render();'));
 for(const stage of ['provider','storage','success']){
  let generations=0,saves=0;
  const env={window:{},lang:'es',authUser:{id:'owner'},authAccessToken:async()=> 'account-token',AbortSignal,File,Uint8Array,atob,fetch:async()=>{generations++;return {ok:stage!=='provider',json:async()=>stage==='provider'?{error:'provider_credit'}:{image:'aW1hZ2U=',type:'image/png'}}},NunaArtifacts:{store:async f=>{saves++;if(stage==='storage')throw Error('private storage error');assert.equal(f.name,'NUNA-imagen.png');return {id:'saved',provider:'r2'}}}};
  vm.createContext(env);vm.runInContext(source,env);
  if(stage==='success')assert.equal((await env.window.NunaImages.create('A fish','owner')).id,'saved');
  else await assert.rejects(env.window.NunaImages.create('A fish','owner'),new RegExp(stage==='provider'?'provider_credit':'image_storage_failed'));
  assert.equal(generations,1);assert.equal(saves,stage==='provider'?0:1);
 }
});
test('voice image tool saves result once and ignores late result after session closes',async()=>{const sent=[],records=[];let pending;const env={Set,voiceGeneration:1,voiceConnection:{send:e=>sent.push(e)},voiceOwner:'owner',voiceChat:{},authUser:{id:'owner'},voiceRecords:records,voiceSetStatus(){},vText:a=>a,storeVoiceRecords(){},window:{NunaImages:{create:async()=>({id:'file',provider:'r2'})}}};vm.createContext(env);const s=fs.readFileSync('voice.js','utf8');vm.runInContext('const voiceClockCalls=new Set();'+s.slice(s.indexOf('async function answerVoiceImage'),s.indexOf('async function answerVoiceClock'))+';this.answer=answerVoiceImage;',env);const call={name:'create_image',call_id:'one',arguments:JSON.stringify({prompt:'A whale'})};await env.answer(call);assert.equal(records.length,1);assert.equal(records[0].files[0].id,'file');assert.equal(JSON.parse(sent[0].item.output).ok,true);await env.answer(call);assert.equal(records.length,1);env.window.NunaImages.create=()=>new Promise(resolve=>pending=resolve);const request=env.answer({...call,call_id:'two'});env.voiceGeneration++;pending({id:'late'});await request;assert.equal(records.length,1);assert.equal(sent.length,2)});
